### ISSUE TITLE
size mismatch for proj_in.weight

### ISSUE THREAD

**Issue by joshua76y** [cubiq/ComfyUI_IPAdapter_plus#118]
Please help: I got the error message and can't run the workflow.("\examples\IPAdapter_Canny.json")

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 466, in apply_ipadapter
    self.ipadapter = IPAdapter(
                     ^^^^^^^^^^
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 175, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
  File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resampler:
        size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1024]).

of cause I have check all the models are in place，I try many way and different node can't get it work, and the workflow pic is here：
![cap](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/42955367/03773d32-93f4-462c-be41-30c59b5d7386)

**Comment by cubiq** [comment]
probably wrong image encoder

**Comment by XTRMsavage** [comment]
> Please help: I got the error message and can't run the workflow.("\examples\IPAdapter_Canny.json")
> 
> ERROR:root:!!! Exception during processing !!! ERROR:root:Traceback (most recent call last): File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 466, in apply_ipadapter self.ipadapter = IPAdapter( ^^^^^^^^^^ File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 175, in **init** self.image_proj_model.load_state_dict(ipadapter_model["image_proj"]) File "F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for Resampler: size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1024]).
> 
> of cause I have check all the models are in place，I try many way and different node can't get it work, and the workflow pic is here： ![cap](https://private-user-images.githubusercontent.com/42955367/288075427-03773d32-93f4-462c-be41-30c59b5d7386.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NjI0NjMsIm5iZiI6MTcwMTg2MjE2MywicGF0aCI6Ii80Mjk1NTM2Ny8yODgwNzU0MjctMDM3NzNkMzItOTNmNC00NjJjLWJlNDEtMzBjNTliNWQ3Mzg2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDExMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZGJiNjMyZDNkY2NjZWI0MTZkZjRhNDJkOGZjNDE4NGJmNDYwNDg1NjQxNDA5YTMzYjc3M2QwZmQ5MjM1NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L0dOxQJdOG6chNPf_zTcRVAiV_WixaS8LvO1HgJxR2E)

Same issue here!

**Comment by sdflysd** [comment]
Same issue here!

**Comment by dishuostec** [comment]
Use https://huggingface.co/h94/IP-Adapter/blob/main/models/image_encoder/model.safetensors as CLIP Viseon model.

**Comment by cubiq** [comment]
closing for inactivity, feel free to reopen if the issue persists
