### ISSUE TITLE
Mask (Atn Mask) no longer working on Mac M2 Ultra after latest update

### ISSUE THREAD

**Issue by pphoto808** [cubiq/ComfyUI_IPAdapter_plus#122]
Error Message:
Error occurred when executing KSampler:  The operator 'aten::upsample_bicubic2d.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

It was working fine maybe 3-4 days ago (current date 12/8/2023). No matter what configuration of encoders and adapters I use, I get the same results with the error. All other IPAdapter features works perfectly...as lone as I don't try to use a mask. Even the example workflows for simple and two mask error. I'm sure it's most likely a Mac thing since I haven't seen any issues reported by Windows users.

**Comment by cubiq** [comment]
can you send the full error message?

it's the first time this got reported so before making any modifications please try to upgrade your environment (pytorch specifically)

**Comment by pphoto808** [comment]
Damn you're fast! I was about to delete the "issue". I was having a problem with the "update all" in Manager where it would not give me the "restart" button. Just fixed that and tried my workflow again with masks and it worked! Thanks again for quick response. And if you are the same who have been posting YouTube vids for IPAdapter---BIG THANKS.

**Comment by beforetea** [comment]
i  had the same problem

i try to "restart" but it dont work

All other IPAdapter features works perfectly...as lone as I don't try to use a mask.

I am also in the m2 

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/nodes.py", line 1355, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/nodes.py", line 1325, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 712, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 618, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 557, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 281, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 271, in forward
    return self.apply_model(*args, **kwargs)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 268, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 248, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/samplers.py", line 222, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/model_base.py", line 85, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/custom_nodes/SeargeSDXL/modules/custom_sdxl_ksampler.py", line 70, in new_unet_forward
    x0 = old_unet_forward(self, x, timesteps, context, y, control, transformer_options, **kwargs)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 847, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 43, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/ldm/modules/attention.py", line 613, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/ldm/modules/attention.py", line 440, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/ldm/modules/diffusionmodules/util.py", line 189, in checkpoint
    return func(*inputs)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/comfy/ldm/modules/attention.py", line 537, in _forward
    n = attn2_replace_patch[block_attn2](n, context_attn2, value_attn2, extra_options)
  File "/Users/design/Documents/ComfyUI_windows_portable/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 472, in __call__
    mask_downsample = F.interpolate(mask.unsqueeze(1), size=(mask_h, mask_w), mode="bicubic").squeeze(1)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/torch/nn/functional.py", line 4073, in interpolate
    return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)
NotImplementedError: The operator 'aten::upsample_bicubic2d.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS

**Comment by beforetea** [comment]
> Damn you're fast! I was about to delete the "issue". I was having a problem with the "update all" in Manager where it would not give me the "restart" button. Just fixed that and tried my workflow again with masks and it worked! Thanks again for quick response. And if you are the same who have been posting YouTube vids for IPAdapter---BIG THANKS.



> Damn you're fast! I was about to delete the "issue". I was having a problem with the "update all" in Manager where it would not give me the "restart" button. Just fixed that and tried my workflow again with masks and it worked! Thanks again for quick response. And if you are the same who have been posting YouTube vids for IPAdapter---BIG THANKS.

How can I solve your problem? After I restart, I still can't use mask

**Comment by dfl** [comment]
I'm getting this error but only when I use attn_mask

NotImplementedError: The operator 'aten::upsample_bicubic2d.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
