### ISSUE TITLE
KeyError: ((1, 1, 224, 3), '|u1')

### ISSUE THREAD

**Issue by wolf95985** [cubiq/ComfyUI_IPAdapter_plus#13]
When I execute IPAdapter_workflow.json,I got this error:

Traceback (most recent call last):
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\PIL\Image.py", line 3080, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 224, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 262, in apply_ipadapter
    clip_embed_zeroed = zeroed_hidden_states(clip_vision)
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 99, in zeroed_hidden_states
    inputs = clip_vision.processor(images=image, return_tensors="pt")
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\image_processing_utils.py", line 446, in __call__
    return self.preprocess(images, **kwargs)
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in preprocess
    images = [self.resize(image=image, size=size, resample=resample) for image in images]
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in <listcomp>
    images = [self.resize(image=image, size=size, resample=resample) for image in images]
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 144, in resize
    return resize(image, size=output_size, resample=resample, data_format=data_format, **kwargs)
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\image_transforms.py", line 275, in resize
    image = to_pil_image(image)
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\image_transforms.py", line 163, in to_pil_image
    return PIL.Image.fromarray(image)
  File "H:\AI\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\PIL\Image.py", line 3083, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 224, 3), |u1

Can you tell me what went wrong?

**Comment by cubiq** [comment]
be sure to have the latest version installed

then double check to have the right models selected (both the image encoder and the IPAdapter). It feels like you are trying to use a plus model with the wrong image encoder.

**Comment by wolf95985** [comment]
You are right, it is normal after replacing the ip-adapter_sd15.bin, but 
ip-adapter-plus_sd15.bin how should I use it?

**Comment by cubiq** [comment]
that's weird, I'd need more info about your configuration. What hardware do you have? what's the comfyui initial message:

like
```
Already up to date.
Total VRAM 24184 MB, total RAM 64211 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
```

**Comment by wolf95985** [comment]
this is my:
Total VRAM 6144 MB, total RAM 16324 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 6GB : cudaMallocAsync
VAE dtype: torch.float32

xformers version or VAE dtype?

**Comment by cubiq** [comment]
can you try the update I just pushed?

**Comment by wolf95985** [comment]
Thanks, everything is working fine now.

**Comment by specblades** [comment]
Got the same error with that line. Prepimg node causing it.

<img width="674" alt="image" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/113993746/fc57b66b-242b-4381-9f54-d765b37767be">

**Comment by specblades** [comment]
@cubiq
