### ISSUE TITLE
The size of tensor a (280) must match the size of tensor b (273) at non-singleton dimension 1

### ISSUE THREAD

**Issue by Largefreedom** [cubiq/ComfyUI_IPAdapter_plus#169]
Currently，i use IPAdapter load two img, one is reference and another is a mask. When the program running on the Ksampers  state, the error  turn out  below, why is that. how do i solve it

#### Error Meggage
**The size of tensor a (280) must match the size of tensor b (273) at non-singleton dimension 1**

**Note: ** the code version of ComfyUI_IPAdapter_plus is the latest.

```p,.ython
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Coding\GithubProject\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Coding\GithubProject\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Coding\GithubProject\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 700, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 533, in process_latent_image
    samples = KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
  File "D:\Coding\GithubProject\ComfyUI\nodes.py", line 1299, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\Coding\GithubProject\ComfyUI\nodes.py", line 1269, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 242, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\sample.py", line 101, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 129, in KSampler_sample
    return _KSampler_sample(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 138, in sample
    return _sample(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\samplers.py", line 622, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\Coding\GithubProject\ComfyUI\comfy\samplers.py", line 561, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\k_diffusion\sampling.py", line 745, in sample_lcm
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\samplers.py", line 285, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\samplers.py", line 275, in forward
    return self.apply_model(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 876, in apply_model
    out = super().apply_model(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\samplers.py", line 272, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "D:\Coding\GithubProject\ComfyUI\comfy\samplers.py", line 252, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\Coding\GithubProject\ComfyUI\comfy\samplers.py", line 226, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\Coding\GithubProject\ComfyUI\comfy\model_base.py", line 85, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 70, in new_unet_forward
    x0 = old_unet_forward(self, x, timesteps, context, y, control, transformer_options, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 868, in forward
    h = forward_timestep_embed(self.middle_block, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "D:\Coding\GithubProject\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 46, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\ldm\modules\attention.py", line 604, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\venve\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\ldm\modules\attention.py", line 431, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "D:\Coding\GithubProject\ComfyUI\comfy\ldm\modules\diffusionmodules\util.py", line 189, in checkpoint
    return func(*inputs)
  File "D:\Coding\GithubProject\ComfyUI\comfy\ldm\modules\attention.py", line 528, in _forward
    n = attn2_replace_patch[block_attn2](n, context_attn2, value_attn2, extra_options)
  File "D:\Coding\GithubProject\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 366, in __call__
    out_ip = out_ip * mask_downsample
RuntimeError: The size of tensor a (280) must match the size of tensor b (273) at non-singleton dimension 1
```

Thanks ,

**Comment by cubiq** [comment]
please share the workflow including the images

**Comment by Largefreedom** [comment]
> please share the workflow including the images
@cubiq  The  link of workflow and images are below, please check it , thanks

https://drive.google.com/drive/folders/1EWg4GtspsOTpR_t0AZ0z2YnGEHSXo6zV

**Comment by cubiq** [comment]
I also need the mask

**Comment by Largefreedom** [comment]
> I also need the mask

@cubiq The mask is generated from the original image and there is no additional mask. See below:

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/33902491/be5c50f0-a828-4850-926c-1b6ef0e97adc)

**Comment by cubiq** [comment]
try to change the size of the mask just a bit, there might be some rounding error

**Comment by Largefreedom** [comment]
thanks your replay，i try it

**Comment by Largefreedom** [comment]
> try to change the size of the mask just a bit, there might be some rounding error

it's work , after i change the size of mask,  the error is disappear
