### ISSUE TITLE
grtting this issue, how to fix this any idea

### ISSUE THREAD

**Issue by Nsiowj** [cubiq/ComfyUI_IPAdapter_plus#174]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 539, in apply_ipadapter
    self.ipadapter = IPAdapter(
                     ^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 213, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resampler:
        size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1664]).

**Comment by cubiq** [comment]
my guess is that you are using the wrong image encoder for the ipadapter model

**Comment by Nsiowj** [comment]
my workflow 
using this IPA ; https://huggingface.co/h94/IP-Adapter/tree/main
[trail.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/13783743/trail.json)

**Comment by cubiq** [comment]
are you using an SD1.5 model on SDXL Turbo?

Turbo is not supported anyway
