### ISSUE TITLE
Error while using Plus models 

### ISSUE THREAD

**Issue by cjtri3d** [cubiq/ComfyUI_IPAdapter_plus#209]
Hi, other models like SD1.5 , lite and Face model are working fine. None of the plus models are working, getting this error. Both the custom node and the comfy are upto date 

ERROR: !!! Exception during processing !!!
ERROR: Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 453, in apply_ipadapter
    clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 105, in zeroed_hidden_states
    outputs = clip_vision.model(pixel_values, intermediate_output=-2)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: CLIPVisionModelWithProjection.forward() got an unexpected keyword argument 'intermediate_output'

**Comment by cjtri3d** [comment]
I checked and it says that comfy is upto date
![Screenshot_2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/153291082/cdf35f58-cef5-4833-b455-69bc4f81ac24)

**Comment by cubiq** [comment]
the extension needs to be updated too
