### ISSUE TITLE
Error when use FaceID plus SDXL 

### ISSUE THREAD

**Issue by nicksonit** [cubiq/ComfyUI_IPAdapter_plus#252]
Hello, when i use faceid plus v2 SDXL i get the error, but faceid sd15 models working is very well. The extension version is Latest current.
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/content/4vkbm9j4/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/4vkbm9j4/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/4vkbm9j4/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/4vkbm9j4/custom_nodes/ipadapter/IPAdapterPlus.py", line 669, in apply_ipadapter
    image_prompt_embeds = self.ipadapter.get_image_embeds_faceid_plus(face_embed.to(self.device, dtype=self.dtype), clip_embed.to(self.device, dtype=self.dtype), weight_v2, faceid_v2)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/4vkbm9j4/custom_nodes/ipadapter/IPAdapterPlus.py", line 333, in get_image_embeds_faceid_plus
    embeds = self.image_proj_model(face_embed, clip_embed, scale=s_scale, shortcut=shortcut)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/4vkbm9j4/custom_nodes/ipadapter/IPAdapterPlus.py", line 129, in forward
    out = self.perceiver_resampler(x, clip_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/4vkbm9j4/custom_nodes/ipadapter/IPAdapterPlus.py", line 59, in forward
    x = self.proj_in(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (257x1664 and 1280x2048)

**Comment by nicksonit** [comment]
Workflow
[workflow (10).json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14127127/workflow.10.json)

**Comment by nicksonit** [comment]
solve - i must use clip vision vit h
