### ISSUE TITLE
UnpicklingError: Weights only load failed.

### ISSUE THREAD

**Issue by Rayray927** [cubiq/ComfyUI_IPAdapter_plus#281]
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 593, in load_ipadapter_model
    model = comfy.utils.load_torch_file(ckpt_path, safe_load=True)
  File "D:\Blender_ComfyUI\ComfyUI\comfy\utils.py", line 20, in load_torch_file
    pl_sd = torch.load(ckpt, map_location=device, weights_only=True)
  File "D:\Blender_ComfyUI\python_embeded\lib\site-packages\torch\serialization.py", line 814, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
_pickle.UnpicklingError: Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 79
```

**Comment by Rayray927** [comment]
putting models at `ComfyUI\models\ipadapter`
