### ISSUE TITLE
Is my version too new???Take a look

### ISSUE THREAD

**Issue by VHS-1** [cubiq/ComfyUI_IPAdapter_plus#305]
!!! Exception during processing !!!
 

 Traceback (most recent call last):
File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 

 File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 698, in apply_ipadapter
raise Exception('InsightFace must be provided for FaceID models.')
Exception: InsightFace must be provided for FaceID models.
 

 Prompt executed in 0.61 seconds
[IPface.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14724178/IPface.json)

**Comment by cubiq** [comment]
you need to use the apply faceid node and provide the insightface model
