### ISSUE TITLE
[Nodes] IPAdapterUnifiedLoader, IPAdapter not found on fresh install ComfyUI,ComfyUI_IPAdapter_plus

### ISSUE THREAD

**Issue by svenhimmelvarg** [cubiq/ComfyUI_IPAdapter_plus#366]
Platform: Linux 
Python: v.3.10.2 

I have a new installation of ComfyUI and ComfyUI_IPAdapter_plus, both at the latest as of 30/04/2024. No other modules are installed and I get the  error where the following Nodes are not found (see screenshot of default workflow at the bottom): 

 *  IPAdapterUnifiedLoader
 *   IPAdapter

The startup screen show this (extra model loading output is editing down for conciseness): 

```bash
(ai)linuxmachin@pop-os:/mnt/sdc1/apps/ComfyUI-Minimal$ python main.py  --listen 0.0.0.0 --multi-user  --disable-xformers 
Total VRAM 24257 MB, total RAM 48091 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Adding extra search path checkpoints /mnt/sdc1/apps/ComfyUI/models/models/checkpoints/
   ...
Adding extra search path vae /mnt/sdc1/apps/autoimport/vae

Import times for custom nodes:
   0.0 seconds: /mnt/sdc1/apps/ComfyUI-Minimal/custom_nodes/websocket_image_save.py
   0.0 seconds: /mnt/sdc1/apps/ComfyUI-Minimal/custom_nodes/ComfyUI_IPAdapter_plus

Starting server

To see the GUI go to: http://0.0.0.0:8188

```

Note that the example custom node and the IP Adapter plus are the only ones installed. 

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/156103639/537a12f3-3972-4230-bf7b-bf7082eddd5d)

All the requirements are met. In fact the requirements are complete enough to run about 30 other custom nodes. This environment is being used to run this minimal set up above. 

Is there any other debug information I can provide to help diagnose this?

**Comment by cubiq** [comment]
can I see the directory structure of the IPAdapter extension you installed?

**Comment by svenhimmelvarg** [comment]
Sure, here you go.  The directory tree taken from  $COMFY_HOME/custom_nodes: 

```bash
linuxmachin@pop-os:/mnt/sdc1/apps/ComfyUI-Minimal/custom_nodes$ tree -L 3
.
├── ComfyUI_IPAdapter_plus
│   ├── examples
│   │   ├── batch_images.jpg
│   │   ├── canny_controlnet.jpg
│   │   ├── FaceID_basic.json
│   │   ├── FaceID_enhanced.json
│   │   ├── FaceID_Plus.json
│   │   ├── FaceID_Plus_v2.json
│   │   ├── face_id_wf.jpg
│   │   ├── face_swap.jpg
│   │   ├── image_weighting.jpg
│   │   ├── inpainting.jpg
│   │   ├── IPAdapter_2_masks.json
│   │   ├── IPAdapter_batch_images.json
│   │   ├── IPAdapter_Canny.json
│   │   ├── IPAdapter_face.json
│   │   ├── IPAdapter_inpaint.json
│   │   ├── IPAdapter_mask.json
│   │   ├── IPAdapter_prepped.json
│   │   ├── IPAdapter_sdxl_vit-h.json
│   │   ├── IPAdapter_weighted.json
│   │   ├── IPAdapter_weight_types.json
│   │   ├── masking.jpg
│   │   ├── noise_example.jpg
│   │   ├── prep_images.jpg
│   │   ├── timestepping.jpg
│   │   └── weight_types.jpg
│   ├── __init__.py
│   ├── IPAdapterPlus.py
│   ├── IPAdapter_workflow.json
│   ├── ipadapter_workflow.png
│   ├── LICENSE
│   ├── models
│   │   └── legacy_models_location.txt
│   ├── __pycache__
│   │   ├── __init__.cpython-310.pyc
│   │   ├── IPAdapterPlus.cpython-310.pyc
│   │   └── resampler.cpython-310.pyc
│   ├── README.md
│   └── resampler.py
├── example
│   ├── example_node.py.example
│   ├── __init__.py
│   ├── __pycache__

```

**Comment by emourdavid** [comment]
I have same problem
Windows 11
Latest ComfyUI + IPAdapter Plus

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/139842563/e56b7f52-9b2e-40bb-9b74-4801e864396b)

**Comment by cubiq** [comment]
@svenhimmelvarg your installation looks broken. delete and reinstall the extension

**Comment by PresTrembleyIIIEsq** [comment]
I'm getting the same issue as OP, and like they did, I completely re-installed ComfyUI and then ComfyUI_IPAdapter_plus. When that still didn't work, I also used the "Try update" button to try updating IPAdapter_plus from within the ComfyUI Manager, with the same result.

I'm also on Linux (Manjaro), but I'm using Python 3.10.11.

**Comment by aleph65** [comment]
Same exact issue here.

**Comment by VIPspawn** [comment]
I'm having a same problem with latest update. When I upload the old update (In that case, this issue doesn't occur.) I only get an error saying "H265" output.

**Comment by VIPspawn** [comment]
> I have similar problem even comfy ipadapter plus node state loaded successfully: ![image](https://private-user-images.githubusercontent.com/139842563/318239741-7f2b64d5-c5bb-40a5-b73c-1448c3cc5938.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDA1NTUsIm5iZiI6MTcxMTkwMDI1NSwicGF0aCI6Ii8xMzk4NDI1NjMvMzE4MjM5NzQxLTdmMmI2NGQ1LWM1YmItNDBhNS1iNzNjLTE0NDhjM2NjNTkzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxNTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzcwYWI5YzAyMmQ2OGM5OTM4NDAwZTc4ZTYwMGQxOTQ5ZTQ0NTRkMDE3MTYwZmFhZWFjN2QwOWUxZDVjY2YwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p7yQKBElU_BO6d6MYTLsQbkZnKsIe5qTxYnPNG4hqe8)
> 
> ![image](https://private-user-images.githubusercontent.com/139842563/318239682-2e0347bb-3a1e-467f-9d12-154d9bc43968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDA1NTUsIm5iZiI6MTcxMTkwMDI1NSwicGF0aCI6Ii8xMzk4NDI1NjMvMzE4MjM5NjgyLTJlMDM0N2JiLTNhMWUtNDY3Zi05ZDEyLTE1NGQ5YmM0Mzk2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxNTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDQ1MDhiOTBhYWJkOTMyMTllN2Y2YTEyOWEyYjE1MDJjNjI0NDMxNDdlODA1ZWVkMzY0ZGRhOTMxZTYwMTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LzguGEOyaFa2cismwrXpmUtlhQMcqoZ6_LtGAH5a5e8)
> 
> Windows 11 Python 3.10.11 Torch 12.1.1cuda121 Latest ComfyUI + IPAdapter Plus
> 
> ![image](https://private-user-images.githubusercontent.com/139842563/318238518-e56b7f52-9b2e-40bb-9b74-4801e864396b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDA1NTUsIm5iZiI6MTcxMTkwMDI1NSwicGF0aCI6Ii8xMzk4NDI1NjMvMzE4MjM4NTE4LWU1NmI3ZjUyLTliMmUtNDBiYi05Yjc0LTQ4MDFlODY0Mzk2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxNTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTY5ZjQ0M2Q1YjhiYTZiZjcwODM0ZjdjNDQ2MTE1MGNkNmJkYTIyM2Q2ODU0NzljYTRjOGE1ZjU2NzUwN2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xDaRHTU--pHR6_N9o136mV2qeNgCrFXpLZnmd4bz58A)
> 
> Updates: When I replace old nodes to new nodes as your suggestion in main page, I have new problem. I changed from light, standard, strength... and it shows like following ![image](https://private-user-images.githubusercontent.com/139842563/318240295-2920aaa4-e6ae-4798-94e0-24af127e96ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MDA1NTUsIm5iZiI6MTcxMTkwMDI1NSwicGF0aCI6Ii8xMzk4NDI1NjMvMzE4MjQwMjk1LTI5MjBhYWE0LWU2YWUtNDc5OC05NGUwLTI0YWYxMjdlOTZlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMVQxNTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGVhZTdlZjBmNTNjOGNjMGMxODVhN2E0MTE2MDUwMjJjOTJhMTMyNmY0Y2JiOWMzNzE0ZTM4NTM2ZmE0MzU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BUjuh6syDSVEq3IX6SBrlOWt6bHlPcWoQOuF-OCdUx4)

I'm having a same problem with latest update. When I upload the old update (In that case, this issue doesn't occur.) I only get an error saying "H265" output.

**Comment by VIPspawn** [comment]
I'm having a same problem with latest update. When I upload the old update (In that case, this issue doesn't occur.) I only get an error saying "H265" output.
![Ekran görüntüsü 2024-03-31 185603](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/85081/37e5829e-cca8-4257-a7f4-109ff7954eb4)

**Comment by cubiq** [comment]
I don't know what the manager is doing. just download this repository and put it into the custom_nodes directory. then download and rename all the nodes

**Comment by VIPspawn** [comment]
> I don't know what the manager is doing. just download this repository and put it into the custom_nodes directory. then download and rename all the nodes

Not Fixed
--
![SS](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/85081/a0f173c4-a475-4b56-9718-054a4608001d)

**Comment by cubiq** [comment]
that is an info box, not an error

**Comment by TheMindExpansionNetwork** [comment]
same issue

**Comment by 2PeteShakur** [comment]
> I'm having a same problem with latest update. When I load the old update (In that case, this issue doesn't occur.) I only get an error saying "H265" output. ![Ekran görüntüsü 2024-03-31 185603](https://private-user-images.githubusercontent.com/85081/318283523-37e5829e-cca8-4257-a7f4-109ff7954eb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTUxNzcsIm5iZiI6MTcxMTkxNDg3NywicGF0aCI6Ii84NTA4MS8zMTgyODM1MjMtMzdlNTgyOWUtY2NhOC00MjU3LWE3ZjQtMTA5ZmY3OTU0ZWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE5NTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMzdiYWNmYTMyODg0NTNiOTc0ZmY0NmMwMmIzM2VhYzEwMzhhNDRjMDE3YjVlMWZkNmE1OThkOGI0ZjhkNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EZqnsbqGu09Lzdkmbc3Nd-UtVxKGRhaXan4TrPl8k1o)

make sure to have a folder named "ipadapter" inside the "model" folder. Put your ipadapter model files inside it, resfresh/reload and it should be fixed.

**Comment by PresTrembleyIIIEsq** [comment]
Not sure if I did anything differently this time, but it worked again for me this morning after doing the following:

1. Reinstall ComfyUI
2. Reinstall ComfyUI_IPAdapter_plus using `git clone` in the `ComfyUI/custom_nodes` folder
3. Re-download all of [the models](https://github.com/cubiq/ComfyUI_IPAdapter_plus#installation) and make sure they have the correct names and locations

**Comment by aleph65** [comment]
@everyone, I watched Olivio's video and was able to fix it. I think I had to press Update All in the manager (top level menu), and I downloaded all IP Adapter files manually into the required directories. I'm running this on Runpod.

https://youtu.be/c8HWDQ67Dvg?si=9bimuy0HLf5AUi5W

Cheers

**Comment by VIPspawn** [comment]
> > I'm having a same problem with latest update. When I load the old update (In that case, this issue doesn't occur.) I only get an error saying "H265" output. ![Ekran görüntüsü 2024-03-31 185603](https://private-user-images.githubusercontent.com/85081/318283523-37e5829e-cca8-4257-a7f4-109ff7954eb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTUxNzcsIm5iZiI6MTcxMTkxNDg3NywicGF0aCI6Ii84NTA4MS8zMTgyODM1MjMtMzdlNTgyOWUtY2NhOC00MjU3LWE3ZjQtMTA5ZmY3OTU0ZWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE5NTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMzdiYWNmYTMyODg0NTNiOTc0ZmY0NmMwMmIzM2VhYzEwMzhhNDRjMDE3YjVlMWZkNmE1OThkOGI0ZjhkNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EZqnsbqGu09Lzdkmbc3Nd-UtVxKGRhaXan4TrPl8k1o)
> 
> make sure to have a folder named "ipadapter" inside the "model" folder. Put your ipadapter model files inside it, resfresh/reload and it should be fixed.

The solution you provided is correct; however, when I replaced the node with a new one, my issue was resolved.
![SS2](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/85081/b8fefb87-b125-4b5e-8e4d-72e3a94d432d)

**Comment by ye7iaserag** [comment]
Here is a solution that works for now to support the workflow hoarders:
- Go to custom_nodes folder.
- Make a copy of ComfyUI_IPAdapter_plus and name it something like ComfyUI_IPAdapter_plus_legacy.
- Checkout commit 6a411dcb2c6c3b91a3aac97adfb080a77ade7d38
- Restart ComfyUI
- ???
- PROFIT???

This is a work around, but I hope the guys here add support to accommodate legacy workflows.

**Comment by garbe-github-support** [comment]
me too，+1

**Comment by samehra** [comment]
What worked for me is adding the line below to the ComfyUI/folder_paths.py file when the folder_names_and_paths dict is created. 

_folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)_

The issue I think is ipadpter path is not getting picked correctly from the extra_model_paths.yaml file

**Comment by Sunsolele** [comment]
> > I'm having a same problem with latest update. When I load the old update (In that case, this issue doesn't occur.) I only get an error saying "H265" output. ![Ekran görüntüsü 2024-03-31 185603](https://private-user-images.githubusercontent.com/85081/318283523-37e5829e-cca8-4257-a7f4-109ff7954eb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MTUxNzcsIm5iZiI6MTcxMTkxNDg3NywicGF0aCI6Ii84NTA4MS8zMTgyODM1MjMtMzdlNTgyOWUtY2NhOC00MjU3LWE3ZjQtMTA5ZmY3OTU0ZWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE5NTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMzdiYWNmYTMyODg0NTNiOTc0ZmY0NmMwMmIzM2VhYzEwMzhhNDRjMDE3YjVlMWZkNmE1OThkOGI0ZjhkNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EZqnsbqGu09Lzdkmbc3Nd-UtVxKGRhaXan4TrPl8k1o)
> 
> make sure to have a folder named "ipadapter" inside the "model" folder. Put your ipadapter model files inside it, resfresh/reload and it should be fixed.

You saved my life! Thanks, buddy!

**Comment by justwjx** [comment]
same issue!!!!!!!!!!

**Comment by POD319** [comment]
This is absolutely an issue with the currently available custom node. I just deleted and redownloaded, and I'm still seeing..

> File "...\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 455, in load_models
raise Exception("IPAdapter model not found.")

Yet if you go to that location, there is a file called legacy_directory_do_not_use.txt

Well, which one is it? 
Unless you put the models in here, the workflows are going to fail.

**Comment by kernel2048** [comment]
This did the trick for me without a full reinstall:
1. Go to ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2. Copy or move all the bin files to ComfyUI\models\ipadapter
3. Queue your workflow again.

Hope this helps too.

**Comment by raochinmay6** [comment]
see this 
`!!! Exception during processing!!! ClipVision model not found.
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 529, in load_models
    raise Exception("ClipVision model not found.")
Exception: ClipVision model not found.`

**Comment by shimib577** [comment]
this worked for me:

go to '.../ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus', then open terminal and put:

git checkout 6a411dcb2c6c3b91a3aac97adfb080a77ade7d38

this switch code to last working state in previous version.

**Comment by KhanBen** [comment]
Try renaming ip-adapter to IP adapter, it worked for me

**Comment by jonnax-dev** [comment]
(1)adding path to the ComfyUI/folder_paths.py as following:
> What worked for me is adding the line below to the ComfyUI/folder_paths.py file when the "folder_names_and_paths" dict is created.
> 
> _folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)_
> 
> The issue I think is ipadpter path is not getting picked correctly from the extra_model_paths.yaml file

(2)then the files in check custom_nodes\ComfyUI_IPAdapter_plus:  if the "utils.py；CrossAttentionPatch.py“ does not exist, that means  ComfyUI_IPAdapter_plus have not been updated to latest verion.
   2.1  reinstall ComfyUI_IPAdapter_plus will be ok.

**Comment by karayakar** [comment]
> What worked for me is adding the line below to the ComfyUI/folder_paths.py file when the "folder_names_and_paths" dict is created.
> 
> _folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)_
> 
> The issue I think is ipadpter path is not getting picked correctly from the extra_model_paths.yaml file

folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ip-adapter")], supported_pt_extensions)

there is a dash between ip-adapter it worked for me.

**Comment by jinruozai** [comment]
Solution for "IPAdapter model not found" error:

The error occurs because the get_ipadapter_file() function in utils.py expects specific filename patterns. Here's how to rename your files:

Current filename -> Required filename

ip-adapter_sd15.safetensors -> ip.adapter.sd15.safetensors
ip-adapter_sdxl_vit-h.safetensors -> ip.adapter.sdxl.vit.h.safetensors
ip-adapter_sd15_light_v11.bin -> sd15.light.v11.bin
ip-adapter_sd15_vit-G.safetensors -> sd15.vit.g.safetensors
ip-adapter_sdxl.safetensors -> ip.adapter.sdxl.safetensors
ip-adapter-plus_sd15.safetensors -> ip.adapter.plus.sd15.safetensors
ip-adapter_sdxl_vit-h.safetensors -> plus.sdxl.vit.h.safetensors
ip-adapter-plus-face_sd15.safetensors -> plus.face.sd15.safetensors
ip-adapter-plus-face_sdxl_vit-h.safetensors -> plus.face.sdxl.vit.h.safetensors
ip-adapter-full-face_sd15.safetensors -> full.face.sd15.safetensors
ip-adapter-faceid-plusv2_sd15.bin -> faceid.plusv2.sd15.bin
ip-adapter-faceid-plusv2_sdxl.bin -> faceid.plusv2.sdxl.bin

Steps:
1. Find your model file in the list
2. Rename it to match the required pattern
3. Restart ComfyUI

**Comment by Hazukiwolf** [comment]
> Solution for "IPAdapter model not found" error:
> 
> The error occurs because the get_ipadapter_file() function in utils.py expects specific filename patterns. Here's how to rename your files:
> 
> Current filename -> Required filename
> 
> ip-adapter_sd15.safetensors -> ip.adapter.sd15.safetensors ip-adapter_sdxl_vit-h.safetensors -> ip.adapter.sdxl.vit.h.safetensors ip-adapter_sd15_light_v11.bin -> sd15.light.v11.bin ip-adapter_sd15_vit-G.safetensors -> sd15.vit.g.safetensors ip-adapter_sdxl.safetensors -> ip.adapter.sdxl.safetensors ip-adapter-plus_sd15.safetensors -> ip.adapter.plus.sd15.safetensors ip-adapter_sdxl_vit-h.safetensors -> plus.sdxl.vit.h.safetensors ip-adapter-plus-face_sd15.safetensors -> plus.face.sd15.safetensors ip-adapter-plus-face_sdxl_vit-h.safetensors -> plus.face.sdxl.vit.h.safetensors ip-adapter-full-face_sd15.safetensors -> full.face.sd15.safetensors ip-adapter-faceid-plusv2_sd15.bin -> faceid.plusv2.sd15.bin ip-adapter-faceid-plusv2_sdxl.bin -> faceid.plusv2.sdxl.bin
> 
> Steps:
> 
> 1. Find your model file in the list
> 2. Rename it to match the required pattern
> 3. Restart ComfyUI

This got it working for me. Why is this even a thing? Is there a good reason to misname the files for download? BTW, where did you get this info?

**Comment by sortafreel** [comment]
@Hazukiwolf Patterns are in the code (check `utils.py:57`, for example). However, it looks like regex, so `.` should be any symbol in patterns like `r'ip.adapter.sdxl\.(safetensors|bin)$'`. So, in my case I just needed to use SDXL ipadapter instead of a regular one, no matter the naming :)

**Comment by romanemul** [comment]
> Solution for "IPAdapter model not found" error:
> 
> The error occurs because the get_ipadapter_file() function in utils.py expects specific filename patterns. Here's how to rename your files:
> 
> Current filename -> Required filename
> 
> ip-adapter_sd15.safetensors -> ip.adapter.sd15.safetensors ip-adapter_sdxl_vit-h.safetensors -> ip.adapter.sdxl.vit.h.safetensors ip-adapter_sd15_light_v11.bin -> sd15.light.v11.bin ip-adapter_sd15_vit-G.safetensors -> sd15.vit.g.safetensors ip-adapter_sdxl.safetensors -> ip.adapter.sdxl.safetensors ip-adapter-plus_sd15.safetensors -> ip.adapter.plus.sd15.safetensors ip-adapter_sdxl_vit-h.safetensors -> plus.sdxl.vit.h.safetensors ip-adapter-plus-face_sd15.safetensors -> plus.face.sd15.safetensors ip-adapter-plus-face_sdxl_vit-h.safetensors -> plus.face.sdxl.vit.h.safetensors ip-adapter-full-face_sd15.safetensors -> full.face.sd15.safetensors ip-adapter-faceid-plusv2_sd15.bin -> faceid.plusv2.sd15.bin ip-adapter-faceid-plusv2_sdxl.bin -> faceid.plusv2.sdxl.bin
> 
> Steps:
> 
> 1. Find your model file in the list
> 2. Rename it to match the required pattern
> 3. Restart ComfyUI

This is it. I got it to work thanks to this reply. How is that possible that author of documentation did not mention that the files use some naming convention ? He just mention rename the files. THANKS AUTHOR !!!
