### ISSUE TITLE
Error: Model Not Found

### ISSUE THREAD

**Issue by gonzalu** [cubiq/ComfyUI_IPAdapter_plus#398]
Getting this error and I can't figure out how to fix it. 

```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 637, in apply_ipadapter
    return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 181, in ipadapter_execute
    raise Exception("insightface model is required for FaceID models")
Exception: insightface model is required for FaceID models
```
I have the models in \ComfyUI\ComfyUI\models\ipadapter\

and here is the workflow ... 

[workflow-wuxia-illustration-workflow-0laBVox12ghCBJPGUGc6-akihungac-openart.ai.json](https://github.com/cubiq/ComfyUI_IPAdapter_plus/files/14886189/workflow-wuxia-illustration-workflow-0laBVox12ghCBJPGUGc6-akihungac-openart.ai.json)

Thanks in advance

**Comment by gonzalu** [comment]
Apologies,

Looks like my InsightFace was not properly installed. 

I followed this video to ultimately fix it:

https://www.youtube.com/watch?v=vCCVxGtCyho
