### ISSUE TITLE
Size mismatch for proj.weight

### ISSUE THREAD

**Issue by gwjd2014** [cubiq/ComfyUI_IPAdapter_plus#4]
Hello. Was trying the workflow included in this repo but keep getting this error:

```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\ComfyUI-Update-9-1-2023\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI-Update-9-1-2023\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI-Update-9-1-2023\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI-Update-9-1-2023\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 245, in apply_ipadapter
    self.ipadapter = IPAdapter(
  File "F:\ComfyUI-Update-9-1-2023\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 90, in __init__
    self.image_proj_model.load_state_dict(self.ipadapter_model["image_proj"])
  File "F:\ComfyUI-Update-9-1-2023\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ImageProjModel:
        size mismatch for proj.weight: copying a param with shape torch.Size([3072, 1024]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
```

Any ideas? Thanks!

**Comment by cubiq** [comment]
what checkpoint are you using?

**Comment by gwjd2014** [comment]
I was trying different models. I used this as well as the default 1.5 Stable diffusion (pruned) model:https://civitai.com/models/102231?modelVersionId=140305

**Comment by cubiq** [comment]
that generally happens when you use the wrong combination of models. all of them have to be SD1.5 or SDXL. Remember you have the clip vision, the ipadapter model and the main checkpoint.

another problem could be in some resolution mismatch. If it doesn't work I'd need to see a readable screen of your workflow

**Comment by gwjd2014** [comment]
I think I was using the wrong Clip Model initially. I redownloaded the sd15 pytorch model, renamed it and doubled checked the IPAdapter model. It stopped the size error but now I see this one:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/143955448/806e93d8-6bc4-4e2c-a87a-d0b057f289cc)

Tested with the default 1.5 that gets downloaded and other models from Civitai:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/143955448/1e4a4fc1-aa94-43b0-b805-ccc7710abbc6)

**Comment by cubiq** [comment]
closing for now, let me know if you still have problems
