### ISSUE TITLE
AttributeError: 'ModelPatcher' object has no attribute 'get_model_object'

### ISSUE THREAD

**Issue by Yaiol** [cubiq/ComfyUI_IPAdapter_plus#412]
Using the ipadapter_faceid.json sample

!!! Exception during processing !!!
Traceback (most recent call last):
  File "I:\apps\bin\sd-comfyui\main\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\apps\bin\sd-comfyui\main\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\apps\bin\sd-comfyui\main\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\apps\bin\sd-comfyui\main\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 637, in apply_ipadapter
    return (ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\apps\bin\sd-comfyui\main\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 327, in ipadapter_execute
    sigma_start = model.get_model_object("model_sampling").percent_to_sigma(start_at)
                  ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModelPatcher' object has no attribute 'get_model_object'

**Comment by cheezecrisp** [comment]
Just now updated and then got same error

**Comment by MagicianHua** [comment]
same exception

**Comment by MagicianHua** [comment]
After I updated comfyui, there was no problem running it

**Comment by Yaiol** [comment]
indeed seems to be related to some change into comfyui, after updating comfyui is working again
closing the issue
