### ISSUE TITLE
ip-adapter-plus_sd15.bin, ip-adapter-plus-face.bin throw

### ISSUE THREAD

**Issue by f-rank** [cubiq/ComfyUI_IPAdapter_plus#45]
Hello,

was trying this custom node, selecting ip-adapter_sd15 and ip-adapter_sd15_light bins works great, though the other two throw the following to console:

got prompt
INFO: the IPAdapter reference image is not a square, CLIPImageProcessor will resize and crop it at the center. If the main focus of the picture is not in the middle the result might not be what you are expecting.
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\PIL\Image.py", line 3089, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 224, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 325, in apply_ipadapter
    clip_embed_zeroed = zeroed_hidden_states(clip_vision, image.shape[0])
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 98, in zeroed_hidden_states
    inputs = clip_vision.processor(images=img, return_tensors="pt")
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\image_processing_utils.py", line 446, in __call__
    return self.preprocess(images, **kwargs)
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in preprocess
    images = [self.resize(image=image, size=size, resample=resample) for image in images]
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in <listcomp>
    images = [self.resize(image=image, size=size, resample=resample) for image in images]
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 144, in resize
    return resize(image, size=output_size, resample=resample, data_format=data_format, **kwargs)
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\image_transforms.py", line 275, in resize
    image = to_pil_image(image)
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\image_transforms.py", line 163, in to_pil_image
    return PIL.Image.fromarray(image)
  File "D:\WORK\conda_envs\ConfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\PIL\Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 224, 3), |u1

Maybe doing something ill advised on my side, maybe some edge case, either way if someone has a clue why those two don't work, would appreciate directions.

**Comment by f-rank** [comment]
Nevermind me, I was one git pull back.
All seems to work well.
Do your git pulls kids!
