### ISSUE TITLE
IPAdapterEncoder.encode() missing 1 required positional argument: 'ipadapter'

### ISSUE THREAD

**Issue by dengfenglai321** [cubiq/ComfyUI_IPAdapter_plus#480]
![企业微信截图_17132543855249](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/50360389/0f2ae2f8-1b05-47e6-8b53-e0985797e486)
执行上面工作流报错如下：
```
ipadapter 92392739 : dict_keys(['clipvision', 'ipadapter', 'insightface'])
Requested to load CLIPVisionModelProjection
Loading 1 new model
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/xxx/workpace/jj/ComfyUI-master/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/xxx/workpace/jj/ComfyUI-master/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/xxx/workpace/jj/ComfyUI-master/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: IPAdapterEncoder.encode() missing 1 required positional argument: 'ipadapter'
```

请问怎么解决呢？

**Comment by cubiq** [comment]
please use standard nodes with no extra extensions and report back

**Comment by dengfenglai321** [comment]
> please use standard nodes with no extra extensions and report back

这个就是example文件夹里面的demo.png工作流。

**Comment by Edwinhei** [comment]
和你一样的问题，你解决了吗

**Comment by cubiq** [comment]
there is not demo.png in the example folder and you are using efficient loader from your screenshot which is not a default node.

also please take the effort to translate your messages, thanks
