### ISSUE TITLE
已经下载好模型的情况下依然提示这个错误代码看上去像是找不到模型？有人能帮我解决吗？

### ISSUE THREAD

**Issue by lzhfdwu007** [cubiq/ComfyUI_IPAdapter_plus#486]
错误代码是
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 452, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

**Comment by huagetai** [comment]
模型文件放的路径不对或者名称不对，可以看官网文档
