### ISSUE TITLE
Cannot import /home/ec2-user/demo/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus module for custom nodes: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (/home/ec2-user/demo/ComfyUI/comfy/clip_vision.py)

### ISSUE THREAD

**Issue by xsw302** [cubiq/ComfyUI_IPAdapter_plus#51]
After I installed the plug-in, the value could not be normal and an error message was reported : 

Traceback (most recent call last):
  File "/home/ec2-user/demo/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ec2-user/demo/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/__init__.py", line 1, in <module>
    from .IPAdapterPlus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/ec2-user/demo/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 7, in <module>
    from comfy.clip_vision import clip_preprocess
ImportError: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (/home/ec2-user/demo/ComfyUI/comfy/clip_vision.py)

Cannot import /home/ec2-user/demo/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus module for custom nodes: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (/home/ec2-user/demo/ComfyUI/comfy/clip_vision.py)

**Comment by cubiq** [comment]
you need to update comfyui, you probably have an older version
