### ISSUE TITLE
Error occurred when executing IPAdapterUnifiedLoaderFaceID: Assertion error

### ISSUE THREAD

**Issue by ak47training** [cubiq/ComfyUI_IPAdapter_plus#521]
Hi

I'm stuck on this. Assertion error of some sort.

Here is a powershell log:
```
Loading 1 new model
INFO: Clip Vision model loaded from H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
INFO: IPAdapter model loaded from H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\ipadapter\ip-adapter-faceid-portrait_sdxl.bin
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
!!! Exception during processing!!!
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 491, in load_models
    self.insightface['model'] = insightface_loader(provider)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 153, in insightface_loader
    model = FaceAnalysis(name="buffalo_l", root=path, providers=[provider + 'ExecutionProvider',])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

```

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/26386206/9321cc39-f6e1-4dd5-9d9a-374daac69f13)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/26386206/27c8c122-1f4d-4528-a1e9-1e6b434ef5b7)

**Comment by cubiq** [comment]
if you use the unified loader you don't need to connect insightface

**Comment by ak47training** [comment]
I've disconnected Insightface pipeline, got the error "Missing Insightface", updated everything with update.bat, got the Dtype mismatch error, followed your instructions to run Comfy with --force-fp16, annnd now I have the same Assertion Error again:

```Loading 1 new model
INFO: Clip Vision model loaded from H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
INFO: IPAdapter model loaded from H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\ipadapter\ip-adapter-faceid-portrait_sdxl.bin
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
!!! Exception during processing!!!
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 491, in load_models
    self.insightface['model'] = insightface_loader(provider)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 153, in insightface_loader
    model = FaceAnalysis(name="buffalo_l", root=path, providers=[provider + 'ExecutionProvider',])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Prompt executed in 437.73 seconds```

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/26386206/3f8d4c2f-3507-4b92-be9f-acd50b0cc855)

Workflow:
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/26386206/7d9a6a82-0aa4-4c0d-afd8-efa8cb8d46d6)

**Comment by cubiq** [comment]
there seems to be a problem with your insightface installation

**Comment by ak47training** [comment]
> there seems to be a problem with your insightface installation

Thank you, cubiq, that has put me on the right trail!

For posterity and future wanderers looking for a solution for this sort of Assertion Error, my final steps to fix this which solved the issue were:

1) Download an archive with Insightface models via this link  https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip
2) Put them into H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l
(five files total as of today May 2nd 2024)
