### ISSUE TITLE
cannot access local variable 'face_image' where it is not associated with a value

### ISSUE THREAD

**Issue by ultimatech-cn** [cubiq/ComfyUI_IPAdapter_plus#522]
Just updating to the latest version. When I am using 
<img width="318" alt="1714522728387" src="https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/142652112/3a0da946-3034-4dfd-8a91-be96f1b342bc">
node.
but got error as following:
```
!!! Exception during processing!!! cannot access local variable 'face_image' where it is not associated with a value
Traceback (most recent call last):
  File "E:\training\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\training\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\training\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\training\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 699, in apply_ipadapter
    return (work_model, face_image, )
            ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'face_image' where it is not associated with a value
```
Any suggestion for that?

**Comment by screan** [comment]
Same issue here

**Comment by cubiq** [comment]
you are using the wrong method in the ipadapter weights

**Comment by githubarooski** [comment]
can this get better error handling then?

**Comment by cubiq** [comment]
yes, totally :smile: but comfy is not that flexible to understand what you are doing wrong. in your case you are just sending an empty image, the node doesn't know why and can't tell you how to fix it

**Comment by ultimatech-cn** [comment]
The error is gone by updating to the latest version
