### ISSUE TITLE
When I try to use VIT-G (medium strength) with the 1.5 model, I get [describe the error message or issue]. It works without problems with SDXL. Could you help me understand this behavior?

### ISSUE THREAD

**Issue by oktetopython** [cubiq/ComfyUI_IPAdapter_plus#523]
[rgthree] Using rgthree's optimized recursive execution.
INFO: Clip Vision model loaded from H:\ComfyUI\ComfyUI\models\clip_vision\CLIP-ViT-bigG-14-laion2B-39B-b160k.bin
INFO: IPAdapter model loaded from H:\ComfyUI\ComfyUI\models\ipadapter\ip-adapter_sdxl.bin
Requested to load CLIPVisionModelProjection
Loading 1 new model
Requested to load SDXL
Loading 1 new model
100%|██████████| 30/30 [00:34<00:00,  1.14s/it]
Prompt executed in 47.07 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
!!! Exception during processing!!! IPAdapter model not found.
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 454, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

Prompt executed in 9.93 seconds

![Snipaste_2024-04-30_22-16-37](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/95683652/da0f5413-395a-4dc0-86e0-83ff44fa8181)

**Comment by oktetopython** [comment]
Got it!
For VIT-G functionality, please ensure you have downloaded and placed the 'ip-adapter_sd15_vit-G.safetensors' model within the 'ipadapter' directory.
