### ISSUE TITLE
IPAdapter model not found.  why?

### ISSUE THREAD

**Issue by samen168** [cubiq/ComfyUI_IPAdapter_plus#541]
[2024-05-08 16:48] preset FACEID PLUS - SD1.5 only
[2024-05-08 16:48] pattern faceid.plus.sd15\.(safetensors|bin)$   list:['ip-adapter-faceid-plusv2_sd15.bin', 'ip-adapter-faceid-plusv2_sdxl.bin', 'ip-adapter-faceid-portrait-v11_sd15.bin', 'ip-adapter-faceid-portrait_sd15.bin', 'ip-adapter-faceid_sd15.bin', 'ip-adapter-faceid_sdxl.bin', 'ip-adapter-full-face_sd15.safetensors', 'ip-adapter-plus-face_sd15.safetensors', 'ip-adapter-plus-face_sdxl_vit-h.safetensors', 'ip-adapter-plus_sd15.safetensors', 'ip-adapter-plus_sdxl_vit-h.safetensors', 'ip-adapter_sd15.safetensors', 'ip-adapter_sd15_light_v11.bin', 'ip-adapter_sd15_vit-G.safetensors', 'ip-adapter_sdxl.safetensors', 'ip-adapter_sdxl_vit-h.safetensors']
[2024-05-08 16:48] ipadapter_file []
[2024-05-08 16:48] !!! Exception during processing!!! IPAdapter model not found.
[2024-05-08 16:48] Traceback (most recent call last):
  File "H:\sd\sd-webui-aki-v4.5-comfy\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\sd\sd-webui-aki-v4.5-comfy\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 456, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

**Comment by samen168** [comment]
Fixed locally
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/31786234/531d91bb-c421-4e1f-80e2-d8956abcd445)

**Comment by cubiq** [comment]
if you follow the default naming it should work

**Comment by samen168** [comment]
> if you follow the default naming it should work

All file names are named according to recommendations

**Comment by samen168** [comment]
> if you follow the default naming it should work

    ip-adapter-faceid-plusv2_sd15.bin
    ip-adapter-faceid-plusv2_sdxl.bin
    ip-adapter-faceid-portrait-v11_sd15.bin
    ip-adapter-faceid-portrait_sd15.bin
    ip-adapter-faceid_sd15.bin
    ip-adapter-faceid_sdxl.bin
    ip-adapter-full-face_sd15.safetensors
    ip-adapter-plus-face_sd15.safetensors
    ip-adapter-plus-face_sdxl_vit-h.safetensors
    ip-adapter-plus_sd15.safetensors
    ip-adapter-plus_sdxl_vit-h.safetensors
    ip-adapter_sd15.safetensors
    ip-adapter_sd15_light_v11.bin
    ip-adapter_sd15_vit-G.safetensors
    ip-adapter_sdxl.safetensors
    ip-adapter_sdxl_vit-h.safetensors
    ip_plus_composition_sd15.safetensors
    ip_plus_composition_sdxl.safetensors

**Comment by cubiq** [comment]
you don't have [ip-adapter-faceid-plus_sd15.bin](https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plus_sd15.bin)

**Comment by samen168** [comment]
> you don't have [ip-adapter-faceid-plus_sd15.bin](https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plus_sd15.bin)

Deprecated [ip-adapter-faceid-plus_sd15.bin](https://huggingface.co/h94/IP-Adapter-FaceID/resolve/main/ip-adapter-faceid-plus_sd15.bin), FaceID plus v1 
so, deleted

**Comment by cubiq** [comment]
so just don't use it :smile:

**Comment by samen168** [comment]
> so just don't use it 😄

对对对，栓Q
