### ISSUE TITLE
too much ram

### ISSUE THREAD

**Issue by Uemuet** [cubiq/ComfyUI_IPAdapter_plus#546]
since the update of ipadapter i get this failure

Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 696, in apply_ipadapter
    work_model, face_image = ipadapter_execute(work_model, ipadapter_model, clip_vision, **ipa_args)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 257, in ipadapter_execute
    img_comp_cond_embeds = encode_image_masked(clipvision, image_composition)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/utils.py", line 161, in encode_image_masked
    pixel_values = clip_preprocess(image.to(clip_vision.load_device)).float()
  File "/content/drive/MyDrive/ComfyUI/comfy/clip_vision.py", line 25, in clip_preprocess
    image = torch.nn.functional.interpolate(image, size=(round(scale * image.shape[2]), round(scale * image.shape[3])), mode="bicubic", antialias=True)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 4027, in interpolate
    return torch._C._nn._upsample_bicubic2d_aa(input, output_size, align_corners, scale_factors)
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 28.18 GiB
Requested               : 12.87 GiB
Device limit            : 39.56 GiB
Free (according to CUDA): 24.81 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

**Comment by cubiq** [comment]
the last update doesn't touch the clip vision encoder. the problem is somewhere else.

**Comment by Uemuet** [comment]
i have it on all workflows, i cant render anymore over 200 frames

**Comment by cubiq** [comment]
the latest update doesn't change the clip vision encoder, maybe you skipped a few updates but it's not the latest. Provide a minimal workflow that triggers the problem or even better try to understand which is the exact update that started showing the issue

**Comment by Uemuet** [comment]
i have the latest version of comfyui and i have it on all my style transfer workflows

**Comment by cubiq** [comment]
- provide a minimal workflow that triggers the problem
- even better try to understand which is the update that actually started the problem, it's not the latest, it must be one of the previous

**Comment by Uemuet** [comment]
it has something to do with comfy new version and pytorch 2.3

**Comment by vanche1212** [comment]
> it has something to do with comfy new version and pytorch 2.3

Wait for comfyui update？
