### ISSUE TITLE
IPAdapter model not found.

### ISSUE THREAD

**Issue by aswordok** [cubiq/ComfyUI_IPAdapter_plus#598]
D:\+AI\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --force-fp16
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-14 08:04:52.594942
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: D:\+AI\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: D:\+AI\ComfyUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.3 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32707 MB
xformers version: 0.0.26.post1+cu118
Forcing FP16.
Set vram state to: NORMAL_VRAM
Device: cuda:0 Quadro P4000 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
Adding extra search path checkpoints D:/+AI/myModels/ComfyUI/models/checkpoints/
Adding extra search path clip_vision D:/+AI/myModels/ComfyUI/models/clip_vision/
Adding extra search path controlnet D:/+AI/myModels/ComfyUI/models/controlnet/
Adding extra search path embeddings D:/+AI/myModels/ComfyUI/models/embeddings/
Adding extra search path loras D:/+AI/myModels/ComfyUI/models/loras/
Adding extra search path upscale_models D:/+AI/myModels/ComfyUI/models/upscale_models/ESRGAN
Adding extra search path upscale_models D:/+AI/myModels/ComfyUI/models/upscale_models/RealESRGAN
Adding extra search path upscale_models D:/+AI/myModels/ComfyUI/models/upscale_models/SwinIR
Adding extra search path vae D:/+AI/myModels/ComfyUI/models/vae/
Adding extra search path animatediff_models D:/+AI/myModels/ComfyUI/models/animatediff_models/
Adding extra search path animatediff_motion_lora D:/+AI/myModels/ComfyUI/models/animatediff_motion_lora/
Adding extra search path hypernetworks D:/+AI/myModels/ComfyUI/models/hypernetworks/
Adding extra search path ipadapter D:/+AI/myModels/ComfyUI/models/ipadapter/
Adding extra search path mmdets D:/+AI/myModels/ComfyUI/models/mmdets/
Adding extra search path sams D:/+AI/myModels/ComfyUI/models/sams/
Adding extra search path ultralytics D:/+AI/myModels/ComfyUI/models/ultralytics/
Adding extra search path style_models D:/+AI/myModels/ComfyUI/models/style_models/
Adding extra search path insightface D:/+AI/myModels/ComfyUI/models/insightface/
Adding extra search path onnx D:/+AI/myModels/ComfyUI/models/onnx/
Adding extra search path antelopev2 D:/+AI/myModels/ComfyUI/models/antelopev2/
Adding extra search path bert-base-uncased D:/+AI/myModels/ComfyUI/models/bert-base-uncased/
Adding extra search path grounding-dino D:/+AI/myModels/ComfyUI/models/grounding-dino/
Adding extra search path instantid D:/+AI/myModels/ComfyUI/models/instantid/
### Loading: ComfyUI-Inspire-Pack (V0.70.1)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2167 [cd07340d] | Released on '2024-05-08'
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> DeepTranslatorNode [Loading]
Node -> ExtrasNode [Loading]
Node -> GoogleTranslateNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Please 'pip install apex'

[rgthree] Loaded 38 extraordinary nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite: `ffmpeg_bin_path` is set to: C:\Program Files\ffmpeg\bin
WAS Node Suite: Finished. Loaded 211 nodes successfully.

        "Opportunities don't happen. You create them." - Chris Grosser

Import times for custom nodes:
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HyperSDXL1StepUnetScheduler
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-EasyNode
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyUI-Custom-Scripts
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.1 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.2 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.3 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CLIPSeg
   0.3 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   2.3 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
   2.5 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   2.6 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID
   2.9 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   9.6 seconds: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
INFO: Clip Vision model loaded from D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
!!! Exception during processing!!! IPAdapter model not found.
Traceback (most recent call last):
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 515, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

Prompt executed in 35.67 seconds

**Comment by aswordok** [comment]
D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes>git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus
Cloning into 'ComfyUI_IPAdapter_plus'...
fatal: unable to access 'https://github.com/cubiq/ComfyUI_IPAdapter_plus/': Failed to connect to github.com port 443 after 21094 ms: Couldn't connect to server

D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes>git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus
Cloning into 'ComfyUI_IPAdapter_plus'...
remote: Enumerating objects: 703, done.
remote: Counting objects: 100% (375/375), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 703 (delta 341), reused 276 (delta 259), pack-reused 328
Receiving objects: 100% (703/703), 4.70 MiB | 54.00 KiB/s, done.
Resolving deltas: 100% (473/473), done.

**Comment by aswordok** [comment]
D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\ipadapter>dir
 驱动器 D 中的卷是 data
 卷的序列号是 781E-3849

 D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\ipadapter 的目录

2024/06/13  17:41    <DIR>          .
2024/06/13  17:24    <DIR>          ..
2024/04/08  20:54       156,558,509 ip-adapter-faceid-plusv2_sd15.bin
2024/04/08  21:04     1,487,555,181 ip-adapter-faceid-plusv2_sdxl.bin
2024/06/13  17:38       156,558,503 ip-adapter-faceid-plus_sd15.bin
2024/04/10  15:21                 0 ip-adapter-faceid-plus_sd15.bin.is.Deprecated.txt
2024/04/08  20:54        64,586,623 ip-adapter-faceid-portrait-v11_sd15.bin
2024/04/10  15:44        64,586,611 ip-adapter-faceid-portrait_sd15.bin
2024/04/10  15:29        64,586,611 ip-adapter-faceid-portrait_sd15.bin.is.Deprecated.txt
2024/04/08  21:02       749,822,515 ip-adapter-faceid-portrait_sdxl.bin
2024/05/07  12:37     1,009,523,411 ip-adapter-faceid-portrait_sdxl_unnorm.bin
2024/04/08  20:53        96,740,574 ip-adapter-faceid_sd15.bin
2024/04/10  15:41     1,071,149,741 ip-adapter-faceid_sdxl.bin
2024/04/08  20:37        43,592,352 ip-adapter-full-face_sd15.safetensors
2024/04/08  20:37        98,183,288 ip-adapter-plus-face_sd15.safetensors
2024/04/08  20:48       847,517,512 ip-adapter-plus-face_sdxl_vit-h.safetensors
2024/04/08  20:35        98,183,288 ip-adapter-plus_sd15.safetensors
2024/04/08  20:45       847,517,512 ip-adapter-plus_sdxl_vit-h.safetensors
2024/04/08  20:33        44,642,768 ip-adapter_sd15.safetensors
2024/04/10  15:31        44,642,768 ip-adapter_sd15_light.safetensors
2024/04/10  15:31                 0 ip-adapter_sd15_light.safetensors.is.Deprecated.txt
2024/04/08  20:34        44,642,977 ip-adapter_sd15_light_v11.bin
2024/04/08  20:38        46,215,640 ip-adapter_sd15_vit-G.safetensors
2024/04/08  20:51       702,585,376 ip-adapter_sdxl.safetensors
2024/04/08  20:41       698,391,064 ip-adapter_sdxl_vit-h.safetensors
2024/04/09  10:23        98,183,728 ip_plus_composition_sd15.safetensors
2024/04/09  10:27       847,517,960 ip_plus_composition_sdxl.safetensors
              25 个文件  9,383,484,512 字节
               2 个目录 848,095,887,360 可用字节

**Comment by aswordok** [comment]
D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip_vision>dir
 驱动器 D 中的卷是 data
 卷的序列号是 781E-3849

 D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\clip_vision 的目录

2024/06/13  23:47    <DIR>          .
2024/06/13  17:24    <DIR>          ..
2024/04/08  18:11     3,689,912,664 CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors
2024/04/08  17:52     2,528,373,448 CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
2024/04/16  23:27     1,710,671,599 clip-vit-large-patch14.bin
2024/03/05  02:13                 0 put_clip_vision_models_here
               4 个文件  7,928,957,711 字节
               2 个目录 848,095,887,360 可用字节


 D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\models\loras 的目录

2024/04/27  22:43    <DIR>          .
2024/06/13  17:24    <DIR>          ..
2024/04/27  22:44    <DIR>          Hyper-SD
2024/04/08  21:06        51,059,544 ip-adapter-faceid-plusv2_sd15_lora.safetensors
2024/04/08  21:09       371,842,896 ip-adapter-faceid-plusv2_sdxl_lora.safetensors
2024/04/10  15:49        51,059,544 ip-adapter-faceid-plus_sd15_lora.safetensors
2024/04/10  15:50                 0 ip-adapter-faceid-plus_sd15_lora.safetensors.is.Deprecated.txt
2024/04/08  21:05        51,059,544 ip-adapter-faceid_sd15_lora.safetensors
2024/04/08  21:08       371,842,896 ip-adapter-faceid_sdxl_lora.safetensors
2024/04/09  10:53    <DIR>          lcm
2024/04/08  23:40    <DIR>          Lora
2024/03/05  02:13                 0 put_loras_here
               7 个文件    896,864,424 字节
               5 个目录 848,095,883,264 可用字节

**Comment by aswordok** [comment]
![x](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/12123396/dde48f66-4bb7-47bc-b172-6b916ca64f45)

**Comment by aswordok** [comment]
ComfyUI_IPAdapter_plus & comfyUI has upgrade to date,What files did I lose?

**Comment by aswordok** [comment]
It is recommended that the error message give a clear message, which directory is missing which file, and where can I download it.

**Comment by aswordok** [comment]
This problem has been solved, refer to:
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/123#issuecomment-1937867603

**Comment by l5ee** [comment]
同样的问题，我按照目录添加了模型，但是还是提示找不到，我是和webUI共享的模型，但是我看这个节点的模型都是在comfyUI下的，不知道是共享的原因吗？还有是不是lora那四个模型也需要放，正在下载中

**Comment by aswordok** [comment]
Make sure you have git installed, then run:
setx /m "Path" "%Path%;C:\Program Files\Git\usr\bin"

sed -i '/checkpoints/ a\folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["instantid"] = ([os.path.join(models_dir, "instantid")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["animatediff_models"] = ([os.path.join(models_dir, "animatediff_models")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["animatediff_motion_lora"] = ([os.path.join(models_dir, "animatediff_motion_lora")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["mmdets"] = ([os.path.join(models_dir, "mmdets")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["sams"] = ([os.path.join(models_dir, "sams")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["ultralytics"] = ([os.path.join(models_dir, "ultralytics")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["insightface"] = ([os.path.join(models_dir, "insightface")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["onnx"] = ([os.path.join(models_dir, "onnx")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["bert-base-uncased"] = ([os.path.join(models_dir, "bert-base-uncased")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"
sed -i '/checkpoints/ a\folder_names_and_paths["grounding-dino"] = ([os.path.join(models_dir, "grounding-dino")], supported_pt_extensions)' "D:\+AI\ComfyUI\ComfyUI_windows_portable\ComfyUI\folder_paths.py"

**Comment by KLL535** [comment]
What file named PLUS? 
It would be nice if someone wrote the real file name.
