### ISSUE TITLE
IPAdapter model not found.

### ISSUE THREAD

**Issue by axior** [cubiq/ComfyUI_IPAdapter_plus#611]
Hello!

Thank you for all your work on IPAdapter nodes, from a fellow italian :) 

I am usually using the classic ipadapter model loader, since I always had issues with IPAdapter unified loader. 
Today I wanted to try it again, and I am encountering issues again, I have checked online and tried some fixes but it does not work.
I am attaching the error comfyui is giving plus a screenshot of my ipadapter models folder. Everything is there and correctly named :(  
![Screenshot 2024-06-25 alle 17 25 40](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/11029351/d3bfaa96-83c7-4616-b67b-c9faa29457fb)
![Screenshot 2024-06-25 alle 17 25 33](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/11029351/ba2c6f39-6860-4bc3-bea2-040e847d90b4)

I am also attaching a screenshot of the cmd when comfyui opens up, there is nothing about ipadapter here, even though I have set a line "#     ipadapter: models/ipadapter/" at the end of the comfyui section of the extra_model_paths.yaml file and still nothing works. Will I have the same results if I use the legacy Ipadapter model loader? 
![Screenshot 2024-06-25 alle 17 33 04](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/11029351/276b68d1-67f9-4ff3-a81f-3aa78a1569d6)

**Comment by kaskaro490** [comment]
same issue here : /

**Comment by bel2k10x** [comment]
Hello Axior,

Clean your folder **\ComfyUI\models\ipadapter** and Download again the checkpoints.
Your folder need to match the pic below. (sorry windows is in French but you see what you have to do)
![Capture](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/121710250/f703c0cb-2e98-462d-9edb-df0393f30ce0)

**Comment by ameen-roayan** [comment]
Hey i am having a similar situation here and the error bit clearly states the model was loaded but something is off it seems.

  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 515, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

Prompt executed in 5.04 seconds
FETCH DATA from: F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
#read_workflow_json_files_all F:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
got prompt
[rgthree] Using rgthree's optimized recursive execution.
INFO: Clip Vision model loaded from F:\AI\ComfyUI\ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
!!! Exception during processing!!! IPAdapter model not found.
Traceback (most recent call last):
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 515, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

Prompt executed in 0.72 seconds

**Comment by axior** [comment]
> Hello Axior,
> 
> Clean your folder **\ComfyUI\models\ipadapter** and Download again the checkpoints. Your folder need to match the pic below. (sorry windows is in French but you see what you have to do) ![Capture](https://private-user-images.githubusercontent.com/121710250/343642297-f703c0cb-2e98-462d-9edb-df0393f30ce0.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NzA2NjMsIm5iZiI6MTcxOTY3MDM2MywicGF0aCI6Ii8xMjE3MTAyNTAvMzQzNjQyMjk3LWY3MDNjMGNiLTJlOTgtNDYyZC05ZWRiLWRmMDM5M2YzMGNlMC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyOVQxNDEyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmRhOTJhOWY4MjgxMjdmNTczNDM3ZTgxZjBlMjRmMmNmNDFkMTE0ZGVmNjFhZGU4ODZkMmQ4NWY1MTk5YWQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.atDkWBCoOnbg4Isc4NyzRJBdO6dwEUepHGBXwqJzzdc)

Thank you! This solved it! I had many checkpoints inside the folder but apparently some were missing :)

**Comment by 3blackbar** [comment]
Wow, this is strange, how about in unified you will give us a choice what model is used , i have plenty of ipadapter models, yet it wants the one i do not have without telling me in cmd which one is missing .
That is not smart way to do stuff, makes it even harder for people to fix when you hide the actual loader.

**Comment by briandw** [comment]
The root problem here is that the code is looking for models that are formatted with dots, like ip.adapter.sd15 and the downloaded files have dashes like ip-adapter-sd15.

**Comment by briandw** [comment]
[I've made a PR with the fix] (https://github.com/cubiq/ComfyUI_IPAdapter_plus/pull/695)

**Comment by cubiq** [comment]
I'll double check this but a dot in a regex covers ANY character, so it should work with dots, underscores, dashes, whatever... and in fact it works for most people. I would need to understand exactly what environment this issue occurs.

**Comment by FVolral** [comment]
> Hello Axior,
> 
> Clean your folder **\ComfyUI\models\ipadapter** and Download again the checkpoints. Your folder need to match the pic below. (sorry windows is in French but you see what you have to do) ![Capture](https://private-user-images.githubusercontent.com/121710250/343642297-f703c0cb-2e98-462d-9edb-df0393f30ce0.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTYwMzksIm5iZiI6MTczMjY1NTczOSwicGF0aCI6Ii8xMjE3MTAyNTAvMzQzNjQyMjk3LWY3MDNjMGNiLTJlOTgtNDYyZC05ZWRiLWRmMDM5M2YzMGNlMC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQyMTE1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjAwZjNhNzJhNjRmN2Y1Y2MwMjAyMTNlZmJhY2YyZDE1ZDI1MTMxYmRhMzRjZWRkOWQ3YjA0MGRmMGNmZDgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8TBYqUKoeTQH0HqobiN9no1W8EUevxLJh2GmxjEq3F4)

I wonder why hardcode the names of the models, instead of loading them with a loader

**Comment by jmpotvinqc** [comment]
Here is my story to finally get it to work.

Error: "IPAdapter model not found." 

In my case this was something really stupid, Following many tutorial at one point I heard that ".bin" should be renamed with an extension of ".pth"...Which I did, and never seem to have any issue with this... Until version 2 of IPADAPTER...

I believe the version 2 of ipadapter enforce the name ".bin" as the official name that the unified loader should look for. 
So I have created link to have access to the original name for each file I have rename the extension form BIN to PTH. 

Change the directory to the models directory I am sharing 
#cd /opt/ComfyUI/models/ipadapter 
I then created the link using Linux "ln –s" command line to create a link form pth to bin...
This is an exmaple of my dozens of file now with PTH extensions 
#ln -s ip-adapter-faceid-portrait_sd15.pth -> ip-adapter-faceid-portrait_sd15.bin 

Note:
Window User's ; Simply rename your files with a ".bin" extensions (Be aware that this can impact other program who are looking for PTH extensions...)
Good Luck...

**Comment by jmpotvinqc** [comment]
Error: "IPAdapter model not found."

Did yo get your ComfyUI to work on a Docker and/or docker-compose?
If you did you have to be aware that if you are using this composer image you are probably missing a bunch of python modiule so that the ipadpater plus program function correctly.

COMFYUI on DOCKER COMPOSER 

I installed the ComfyUI within a docker-composer. 
Sure I was afraid about compatibility issues with docker and NVIDIA but lucky me! So far it works good. 

I did made some changes to the original compose.yaml file to have the models folder look outside the docker container. 

compose.yaml : 
services: 
  comfyui-nvidia: 
    image: mmartial/comfyui-nvidia-docker:latest 
    container_name: comfyui-nvidia 
    ports: 
      - 8188:8188 
    volumes: 
      - ./run:/comfy/mnt 
      - /opt/ComfyUI/models:/comfy/mnt/ComfyUI/models 
  
    restart: unless-stopped 
    environment: 
      - WANTED_UID=1000 
      - WANTED_GID=1000 
      - NVIDIA_VISIBLE_DEVICES=all 
      - NVIDIA_DRIVER_CAPABILITIES=all 
    deploy: 
      resources: 
        reservations: 
          devices: 
            - driver: nvidia 
              count: all 
              capabilities: 
                - gpu 
                - compute 
                - utility
With the docker container installed and running,   I was able to use my ComfyUI with docker on 127.0.0.1:8188,
All the comfy web GUI tools are working great it even comes with the "Manager (Comfy Manager Menu)" already installed!
All went well until I wanted to use ipadapter plus v2.
I used th Manager to insatll the module following a tutoriual.
The Python module was installed successfully according to the module manager.
But in reality this is not true!
The program cannot work has the docker container from "mmartial/comfyui-nvidia-docker:latest" is not build with the ipadapter already installed,  so the python libraries requirements are missing.
The GITHUB for the ComfyUI_IPAdapter_plus does not have steps with requirements.txt file to make sure you have all the neceesary libraries in order to get the to IPAdpadterPlus.py to work .

What I did . 
Go into my docker installation folder : 
#cd /opt/docker/comfyui 
List the docker container info so I can use the container name to access it. 
user@fedora:/opt/docker/comfyui$ docker-compose ps 
           Name                          Command               State                    Ports                   
--------------------------------------------------------------------------------------------------------------- 
0656cc0dcccf_comfyui-nvidia   /opt/nvidia/nvidia_entrypo ...   Up      0.0.0.0:8188->8188/tcp,:::8188 >8188/tcp 

Now that I have the name I "Entered" into my docker container: 
Example : 
#enter comfyui-nvidia 
Move into the folder where the creator of this container decided to do the installation   
#cd mnt/ComfyUI/ 
Then I moved into the ComfyUI_IPAdapter_plus" folder : 
#cd custom_nodes/ComfyUI_IPAdapter_plus/ 
Where I tested manually the main python program:
#cd /comfy/mnt/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus 
#python3 IPAdapterPlus.py 
 
...And this program was a mess!... It was missing a bunch of python libraries in order to work correctly!

Here is my result after installing all the necessary libraries for the IPAdapterPlus.py  to be stop complaining : 
#cd /comfy/mnt/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus 
#python3 IPAdapterPlus.py 
...
Traceback (most recent call last):
  File "/comfy/mnt/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 19, in <module>
    from .image_proj_models import MLPProjModel, MLPProjModelFaceId, ProjModelFaceIdPlus, Resampler, ImageProjModel
ImportError: attempted relative import with no known parent package
OK I still got error but they looked more legitimate like mandatory missing parameter to the command line...
Instead of error like:
- MISSING python module psutils
- MISSING python module einops 
- MISSING module torch
- MISSING module diffusers
-etc...

I dont pretend knowing all the requirements for IPAdapterPlus.py
But it would be great to see a requirements.txt file appearing within the main GITHUB repository!!!.
Goog Luck!

NOTE ABOUT "ENTER": 
Do not look for the "enter" command line in docker has this is a Bash shell program I use to simplify my life instead of remembering the docker command line to enter my docker container.

**Comment by mandowo** [comment]
> Hello Axior,
> 
> Clean your folder **\ComfyUI\models\ipadapter** and Download again the checkpoints. Your folder need to match the pic below. (sorry windows is in French but you see what you have to do) ![Capture](https://private-user-images.githubusercontent.com/121710250/343642297-f703c0cb-2e98-462d-9edb-df0393f30ce0.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MTkxMTQsIm5iZiI6MTczNjUxODgxNCwicGF0aCI6Ii8xMjE3MTAyNTAvMzQzNjQyMjk3LWY3MDNjMGNiLTJlOTgtNDYyZC05ZWRiLWRmMDM5M2YzMGNlMC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMFQxNDIwMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWNlYWZmNDZhZDRjN2RmYzdlOWQwOGZhNzM3YjgxNGFlMWMzNDdkNzY4NGY1MmRhNWZkNDI1YzNlZmRkOGU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MtXAJxVktwG0NfT5JgSH6oo6XjAcc_sKvqbg_14Un1I)

Where to get the file ip-adapter potrait?
mine is here, and the similiar issue : 
<img width="927" alt="Screenshot 2025-01-10 213701" src="https://github.com/user-attachments/assets/7df793a1-b68f-4784-8ac6-2d5fbbad0695" />
<img width="797" alt="sad" src="https://github.com/user-attachments/assets/21e32d28-5d15-4700-98ef-0aaecf64d711" />

**Comment by dzy1128** [comment]
按照匹配规则命名才行：
if preset.startswith("light"):
        if is_sdxl:
            raise Exception("light model is not supported for SDXL")
        pattern = r'sd15.light.v11\.(safetensors|bin)$'
        # if v11 is not found, try with the old version
        if not [e for e in ipadapter_list if re.search(pattern, e, re.IGNORECASE)]:
            pattern = r'sd15.light\.(safetensors|bin)$'
    elif preset.startswith("standard"):
        if is_sdxl:
            pattern = r'ip.adapter.sdxl.vit.h\.(safetensors|bin)$'
        else:
            pattern = r'ip.adapter.sd15\.(safetensors|bin)$'
    elif preset.startswith("vit-g"):
        if is_sdxl:
            pattern = r'ip.adapter.sdxl\.(safetensors|bin)$'
        else:
            pattern = r'sd15.vit.g\.(safetensors|bin)$'
    elif preset.startswith("plus ("):
        if is_sdxl:
            pattern = r'plus.sdxl.vit.h\.(safetensors|bin)$'
        else:
            pattern = r'ip.adapter.plus.sd15\.(safetensors|bin)$'
    elif preset.startswith("plus face"):
        if is_sdxl:
            pattern = r'plus.face.sdxl.vit.h\.(safetensors|bin)$'
        else:
            pattern = r'plus.face.sd15\.(safetensors|bin)$'
    elif preset.startswith("full"):
        if is_sdxl:
            raise Exception("full face model is not supported for SDXL")
        pattern = r'full.face.sd15\.(safetensors|bin)$'
    elif preset.startswith("faceid portrait ("):
        if is_sdxl:
            pattern = r'portrait.sdxl\.(safetensors|bin)$'
        else:
            pattern = r'portrait.v11.sd15\.(safetensors|bin)$'
            # if v11 is not found, try with the old version
            if not [e for e in ipadapter_list if re.search(pattern, e, re.IGNORECASE)]:
                pattern = r'portrait.sd15\.(safetensors|bin)$'
        is_insightface = True
    elif preset.startswith("faceid portrait unnorm"):
        if is_sdxl:
            pattern = r'portrait.sdxl.unnorm\.(safetensors|bin)$'
        else:
            raise Exception("portrait unnorm model is not supported for SD1.5")
        is_insightface = True
    elif preset == "faceid":
        if is_sdxl:
            pattern = r'faceid.sdxl\.(safetensors|bin)$'
            lora_pattern = r'faceid.sdxl.lora\.safetensors$'
        else:
            pattern = r'faceid.sd15\.(safetensors|bin)$'
            lora_pattern = r'faceid.sd15.lora\.safetensors$'
        is_insightface = True
    elif preset.startswith("faceid plus -"):
        if is_sdxl:
            raise Exception("faceid plus model is not supported for SDXL")
        pattern = r'faceid.plus.sd15\.(safetensors|bin)$'
        lora_pattern = r'faceid.plus.sd15.lora\.safetensors$'
        is_insightface = True
    elif preset.startswith("faceid plus v2"):
        if is_sdxl:
            pattern = r'faceid.plusv2.sdxl\.(safetensors|bin)$'
            lora_pattern = r'faceid.plusv2.sdxl.lora\.safetensors$'
        else:
            pattern = r'faceid.plusv2.sd15\.(safetensors|bin)$'
            lora_pattern = r'faceid.plusv2.sd15.lora\.safetensors$'
        is_insightface = True
    # Community's models
    elif preset.startswith("composition"):
        if is_sdxl:
            pattern = r'plus.composition.sdxl\.safetensors$'
        else:
            pattern = r'plus.composition.sd15\.safetensors$'
    else:
        raise Exception(f"invalid type '{preset}'")
