### ISSUE TITLE
cannot import name 'clip_preprocess' from 'comfy.clip_vision

### ISSUE THREAD

**Issue by Squallpka1** [cubiq/ComfyUI_IPAdapter_plus#65]
Updated all ComfyUI because its been awhile and wanna see new stuff and i see there is no IPAdapter node i can use. Looking at terminal i realize its say

` 0.0 seconds (IMPORT FAILED): D:\ComfyUI SDXL Ultimate Workflow\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus`

Try to get the trackback and get

```
Traceback (most recent call last):
  File "D:\ComfyUI SDXL Ultimate Workflow\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI SDXL Ultimate Workflow\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\__init__.py", line 1, in <module>
    from .IPAdapterPlus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI SDXL Ultimate Workflow\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 7, in <module>
    from comfy.clip_vision import clip_preprocess
ImportError: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (D:\ComfyUI SDXL Ultimate Workflow\ComfyUI\comfy\clip_vision.py)

Cannot import D:\ComfyUI SDXL Ultimate Workflow\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus module for custom nodes: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (D:\ComfyUI SDXL Ultimate Workflow\ComfyUI\comfy\clip_vision.py)
```

**Comment by Squallpka1** [comment]
Resolved. I update the comfyUI via /update/update_comfyui.bat file. Seem the update all and update comfyUI via web not really update ComfyUI.
