### ISSUE TITLE
ModuleNotFoundError: No module named 'node_helpers'

### ISSUE THREAD

**Issue by sirouk** [cubiq/ComfyUI_IPAdapter_plus#658]
When standing up ComfuyUI with the `ComfyUI_IPAdapter_plus` custom_node on commit `78ac59c61c8caf33e3419d2c8f70838b2da0fb04`, it's throwing this error:

```
VAE dtype: torch.float32
Using pytorch cross attention
Traceback (most recent call last):
  File "/home/sirouk/ComfyUI/nodes.py", line 1889, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/sirouk/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/__init__.py", line 17, in <module>
    from .IPAdapterPlus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/sirouk/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 7, in <module>
    from node_helpers import conditioning_set_values
```

**Comment by cubiq** [comment]
you probably have an old version of comfy installed

**Comment by sirouk** [comment]
That was it! thank you :)
