### ISSUE TITLE
Help resolve exceptions   求大佬看看~  下面提示的插件我都最新了。。。

### ISSUE THREAD

**Issue by shenshu666** [cubiq/ComfyUI_IPAdapter_plus#665]
!!! Exception during processing!!! Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
  query.dtype: torch.float16
  key.dtype  : torch.float32
  value.dtype: torch.float32
Traceback (most recent call last):
  File "D:\app\ComfyUI-aki\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\app\ComfyUI-aki\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\app\ComfyUI-aki\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 5252, in run
    return process_sample_state(pipe, samp_model, samp_clip, samp_samples, samp_vae, samp_seed, samp_positive, samp_negative, steps, start_step, last_step, cfg, sampler_name, scheduler, denoise, image_output, link_id, save_prefix, tile_size, prompt, extra_pnginfo, my_unique_id, preview_latent, force_full_denoise, disable_noise, samp_custom)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI-Easy-Use\py\easyNodes.py", line 5036, in process_sample_state
    samp_samples = sampler.common_ksampler(samp_model, samp_seed, steps, cfg, sampler_name, scheduler, samp_positive, samp_negative, samp_samples, denoise=denoise, preview_latent=preview_latent, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, disable_noise=disable_noise)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI-Easy-Use\py\libs\sampler.py", line 116, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative,
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\sampling.py", line 92, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 112, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "D:\app\ComfyUI-aki\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1447, in KSampler_sample
    return _KSampler_sample(*args, **kwargs)
  File "D:\app\ComfyUI-aki\comfy\samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1470, in sample
    return _sample(*args, **kwargs)
  File "D:\app\ComfyUI-aki\comfy\samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\app\ComfyUI-aki\comfy\samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\app\ComfyUI-aki\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\app\ComfyUI-aki\comfy\samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\app\ComfyUI-aki\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\app\ComfyUI-aki\comfy\k_diffusion\sampling.py", line 143, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "D:\app\ComfyUI-aki\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 993, in __call__
    return self.predict_noise(*args, **kwargs)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1043, in predict_noise
    out = super().predict_noise(*args, **kwargs)
  File "D:\app\ComfyUI-aki\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "D:\app\ComfyUI-aki\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "D:\app\ComfyUI-aki\comfy\samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 64, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "D:\app\ComfyUI-aki\comfy\model_base.py", line 115, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\app\ComfyUI-aki\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\app\ComfyUI-aki\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\app\ComfyUI-aki\custom_nodes\FreeU_Advanced\nodes.py", line 176, in __temp__forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "D:\app\ComfyUI-aki\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 44, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "D:\app\ComfyUI-aki\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\app\ComfyUI-aki\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\app\ComfyUI-aki\comfy\ldm\modules\attention.py", line 694, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "D:\app\ComfyUI-aki\python\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\app\ComfyUI-aki\python\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI-Easy-Use\py\layer_diffuse\attension_sharing.py", line 253, in forward
    return func(self, x, context, transformer_options)
  File "D:\app\ComfyUI-aki\comfy\ldm\modules\attention.py", line 618, in forward
    n = attn2_replace_patch[block_attn2](n, context_attn2, value_attn2, extra_options)
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI_IPAdapter_plus\CrossAttentionPatch.py", line 26, in __call__
    out = out + callback(out, q, k, v, extra_options, **self.kwargs[i])
  File "D:\app\ComfyUI-aki\custom_nodes\ComfyUI_IPAdapter_plus\CrossAttentionPatch.py", line 169, in ipadapter_attention
    out_ip = optimized_attention(q, ip_k, ip_v, extra_options["n_heads"])
  File "D:\app\ComfyUI-aki\comfy\ldm\modules\attention.py", line 380, in attention_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=mask)
  File "D:\app\ComfyUI-aki\python\lib\site-packages\xformers\ops\fmha\__init__.py", line 223, in memory_efficient_attention
    return _memory_efficient_attention(
  File "D:\app\ComfyUI-aki\python\lib\site-packages\xformers\ops\fmha\__init__.py", line 321, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "D:\app\ComfyUI-aki\python\lib\site-packages\xformers\ops\fmha\__init__.py", line 334, in _memory_efficient_attention_forward
    inp.validate_inputs()
  File "D:\app\ComfyUI-aki\python\lib\site-packages\xformers\ops\fmha\common.py", line 121, in validate_inputs
    raise ValueError(
ValueError: Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
  query.dtype: torch.float16

**Comment by cubiq** [comment]
try to run comfy in --force-fp16 mode

**Comment by shenshu666** [comment]
> try to run comfy in --force-fp16 mode

**Comment by shenshu666** [comment]
> try to run comfy in --force-fp16 mode

![e2270407e84d69d899a92b214e55b25](https://github.com/user-attachments/assets/97aa0ef5-8808-40a0-a97e-7bc2cb5439eb)

**Comment by shenshu666** [comment]
n

> try to run comfy in --force-fp16 mode

I don't have main py

**Comment by shenshu666** [comment]
> try to run comfy in --force-fp16 mode
Have discovered
![image](https://github.com/user-attachments/assets/e3ab068e-8b07-4309-8397-379323fa86f5)

**Comment by Remember2015** [comment]
> > try to run comfy in --force-fp16 mode
> 
> ![e2270407e84d69d899a92b214e55b25](https://private-user-images.githubusercontent.com/131776613/353757179-97aa0ef5-8808-40a0-a97e-7bc2cb5439eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDA0NzAsIm5iZiI6MTcyMjUwMDE3MCwicGF0aCI6Ii8xMzE3NzY2MTMvMzUzNzU3MTc5LTk3YWEwZWY1LTg4MDgtNDBhMC1hOTdlLTdiYzJjYjU0MzllYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwODE2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWU0NmZlMjQ3ODg1Y2MzMGI0NTc4MDkwYjRlMDg2MTg1YzAyNTNkY2FiYThiN2M4NTNjMGEwNDNhZmI4MGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wc0R0D5lyfuOPiTH1pJaYUO-akuLy4gfdevCl1uAK4I)

看看 comfyui/main.py 路径对不对....

**Comment by shenshu666** [comment]
> > > try to run comfy in --force-fp16 mode
> > 
> > 
> > ![e2270407e84d69d899a92b214e55b25](https://private-user-images.githubusercontent.com/131776613/353757179-97aa0ef5-8808-40a0-a97e-7bc2cb5439eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDA0NzAsIm5iZiI6MTcyMjUwMDE3MCwicGF0aCI6Ii8xMzE3NzY2MTMvMzUzNzU3MTc5LTk3YWEwZWY1LTg4MDgtNDBhMC1hOTdlLTdiYzJjYjU0MzllYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwODE2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWU0NmZlMjQ3ODg1Y2MzMGI0NTc4MDkwYjRlMDg2MTg1YzAyNTNkY2FiYThiN2M4NTNjMGEwNDNhZmI4MGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wc0R0D5lyfuOPiTH1pJaYUO-akuLy4gfdevCl1uAK4I)
> 
> 看看 comfyui/main.py 路径对不对....

谢谢已经解决了~     我用的秋叶的包。秋叶的程序不能调fp16  。最后我cmd 解决的
