### ISSUE TITLE
IPAadapterInsightFaceLoader DLL load failed while importing onnx_cpp2py_export

### ISSUE THREAD

**Issue by LuciusJax** [cubiq/ComfyUI_IPAdapter_plus#700]
# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapterInsightFaceLoader
- **Exception Type:** Exception
- **Exception Message:** DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
## Stack Trace
```
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 674, in load_insightface
    return (insightface_loader(provider, model_name=model_name),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 161, in insightface_loader
    raise Exception(e)

```
## System Information
- **ComfyUI Version:** v0.2.0
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12878086144
  - **VRAM Free:** 9983698936
  - **Torch VRAM Total:** 1644167168
  - **Torch VRAM Free:** 7546872

## Logs
```
2024-09-01 20:44:38,572 - root - INFO - Total VRAM 12282 MB, total RAM 32694 MB
2024-09-01 20:44:38,573 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-01 20:44:38,574 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-01 20:44:38,574 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
2024-09-01 20:44:44,255 - root - INFO - Using pytorch cross attention
2024-09-01 20:44:45,590 - root - INFO - [Prompt Server] web root: D:\A.I\ComfyUI_windows_portable\ComfyUI\web
2024-09-01 20:44:53,164 - root - WARNING - Traceback (most recent call last):
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

2024-09-01 20:44:53,165 - root - WARNING - Cannot import D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
2024-09-01 20:44:53,395 - root - INFO - 
Import times for custom nodes:
2024-09-01 20:44:53,396 - root - INFO -    0.0 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-01 20:44:53,397 - root - INFO -    0.0 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\extended-saveimage-comfyui
2024-09-01 20:44:53,397 - root - INFO -    0.0 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Ib_CustomNodes
2024-09-01 20:44:53,397 - root - INFO -    0.0 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-01 20:44:53,398 - root - INFO -    0.0 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-09-01 20:44:53,398 - root - INFO -    0.0 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\save-image-extended-comfyui
2024-09-01 20:44:53,399 - root - INFO -    0.0 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-01 20:44:53,399 - root - INFO -    0.0 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-09-01 20:44:53,400 - root - INFO -    0.0 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-01 20:44:53,400 - root - INFO -    0.1 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-01 20:44:53,401 - root - INFO -    0.1 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-01 20:44:53,401 - root - INFO -    0.2 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-01 20:44:53,401 - root - INFO -    0.6 seconds: D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-09-01 20:44:53,402 - root - INFO -    6.1 seconds (IMPORT FAILED): D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
2024-09-01 20:44:53,402 - root - INFO - 
2024-09-01 20:44:53,416 - root - INFO - Starting server

2024-09-01 20:44:53,416 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-01 20:45:10,983 - root - INFO - got prompt
2024-09-01 20:45:11,315 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-09-01 20:45:11,319 - root - INFO - model_type EPS
2024-09-01 20:45:11,990 - root - INFO - Using pytorch attention in VAE
2024-09-01 20:45:11,991 - root - INFO - Using pytorch attention in VAE
2024-09-01 20:45:12,451 - root - INFO - Requested to load SDXLClipModel
2024-09-01 20:45:12,451 - root - INFO - Loading 1 new model
2024-09-01 20:45:12,462 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-09-01 20:45:17,194 - root - WARNING - Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
2024-09-01 20:45:17,531 - root - WARNING - Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
2024-09-01 20:45:39,749 - root - ERROR - !!! Exception during processing !!! DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
2024-09-01 20:45:39,753 - root - ERROR - Traceback (most recent call last):
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 159, in insightface_loader
    from insightface.app import FaceAnalysis
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "D:\A.I\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 674, in load_insightface
    return (insightface_loader(provider, model_name=model_name),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\A.I\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 161, in insightface_loader
    raise Exception(e)
Exception: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

2024-09-01 20:45:39,755 - root - INFO - Prompt executed in 28.76 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by ductiletoaster** [comment]
I am running into the same issue. Any resolution or work around? I've tried to lock Onnx to version 1.16.2 which was suggested on another thread but that didn't seem to help. 

```
# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapterUnifiedLoaderFaceID
- **Exception Type:** Exception
- **Exception Message:** DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
## Stack Trace
```
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 610, in load_models
    self.insightface['model'] = insightface_loader(provider)

  File "E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 161, in insightface_loader
    raise Exception(e)

```
## System Information
- **ComfyUI Version:** v0.2.2-90-g2c641e6
- **Arguments:** E:\StabilityMatrix\Data\Packages\ComfyUI\main.py --preview-method auto
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170825216
  - **VRAM Free:** 14095165432
  - **Torch VRAM Total:** 1711276032
  - **Torch VRAM Free:** 41101304

## Logs
```
2024-10-10 22:33:07,037 - root - INFO - Total VRAM 16375 MB, total RAM 32678 MB
2024-10-10 22:33:07,037 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-10 22:33:07,038 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-10 22:33:07,038 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
2024-10-10 22:33:10,339 - root - INFO - Using pytorch cross attention
2024-10-10 22:33:11,557 - root - INFO - [Prompt Server] web root: E:\StabilityMatrix\Data\Packages\ComfyUI\web
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path checkpoints E:\StabilityMatrix\Data\Models\StableDiffusion
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path vae E:\StabilityMatrix\Data\Models\VAE
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path loras E:\StabilityMatrix\Data\Models\Lora
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path loras E:\StabilityMatrix\Data\Models\LyCORIS
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path upscale_models E:\StabilityMatrix\Data\Models\ESRGAN
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path upscale_models E:\StabilityMatrix\Data\Models\RealESRGAN
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path upscale_models E:\StabilityMatrix\Data\Models\SwinIR
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path embeddings E:\StabilityMatrix\Data\Models\TextualInversion
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path hypernetworks E:\StabilityMatrix\Data\Models\Hypernetwork
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path controlnet E:\StabilityMatrix\Data\Models\ControlNet
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path controlnet E:\StabilityMatrix\Data\Models\T2IAdapter
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path clip E:\StabilityMatrix\Data\Models\CLIP
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path clip_vision E:\StabilityMatrix\Data\Models\InvokeClipVision
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path diffusers E:\StabilityMatrix\Data\Models\Diffusers
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path gligen E:\StabilityMatrix\Data\Models\GLIGEN
2024-10-10 22:33:11,560 - root - INFO - Adding extra search path vae_approx E:\StabilityMatrix\Data\Models\ApproxVAE
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path ipadapter E:\StabilityMatrix\Data\Models\IpAdapter
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path ipadapter E:\StabilityMatrix\Data\Models\InvokeIpAdapters15
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path ipadapter E:\StabilityMatrix\Data\Models\InvokeIpAdaptersXl
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path prompt_expansion E:\StabilityMatrix\Data\Models\PromptExpansion
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path unet E:\StabilityMatrix\Data\Models\unet
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path ultralytics E:\StabilityMatrix\Data\Models\Ultralytics
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path ultralytics_bbox E:\StabilityMatrix\Data\Models\Ultralytics\bbox
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path ultralytics_segm E:\StabilityMatrix\Data\Models\Ultralytics\segm
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path sams E:\StabilityMatrix\Data\Models\Sams
2024-10-10 22:33:11,561 - root - INFO - Adding extra search path diffusion_models E:\StabilityMatrix\Data\Models\unet
2024-10-10 22:33:12,744 - root - INFO - Total VRAM 16375 MB, total RAM 32678 MB
2024-10-10 22:33:12,744 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-10 22:33:12,744 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-10 22:33:12,745 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
2024-10-10 22:33:18,218 - root - INFO - 
Import times for custom nodes:
2024-10-10 22:33:18,218 - root - INFO -    0.0 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-10 22:33:18,218 - root - INFO -    0.0 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-10 22:33:18,218 - root - INFO -    0.0 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-10 22:33:18,218 - root - INFO -    0.0 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-10 22:33:18,218 - root - INFO -    0.0 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-10 22:33:18,218 - root - INFO -    0.0 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-10 22:33:18,218 - root - INFO -    0.1 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-10 22:33:18,218 - root - INFO -    0.1 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-10-10 22:33:18,219 - root - INFO -    0.3 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-10 22:33:18,219 - root - INFO -    0.5 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-10 22:33:18,219 - root - INFO -    1.6 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-10 22:33:18,219 - root - INFO -    3.4 seconds: E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfy_mtb
2024-10-10 22:33:18,219 - root - INFO - 
2024-10-10 22:33:18,227 - root - INFO - Starting server

2024-10-10 22:33:18,227 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-10 22:33:57,354 - root - INFO - got prompt
2024-10-10 22:33:57,683 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-10 22:33:57,684 - root - INFO - model_type EPS
2024-10-10 22:34:03,238 - root - INFO - Using pytorch attention in VAE
2024-10-10 22:34:03,240 - root - INFO - Using pytorch attention in VAE
2024-10-10 22:34:04,368 - root - INFO - Requested to load SDXLClipModel
2024-10-10 22:34:04,368 - root - INFO - Loading 1 new model
2024-10-10 22:34:04,386 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-10 22:34:13,143 - root - ERROR - !!! Exception during processing !!! DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.
2024-10-10 22:34:13,153 - root - ERROR - Traceback (most recent call last):
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 159, in insightface_loader
    from insightface.app import FaceAnalysis
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\__init__.py", line 16, in <module>
    from . import model_zoo
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
    from .model_zoo import get_model
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
    from .arcface_onnx import *
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
    import onnx
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\onnx\__init__.py", line 77, in <module>
    from onnx.onnx_cpp2py_export import ONNX_ML
ImportError: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 610, in load_models
    self.insightface['model'] = insightface_loader(provider)
  File "E:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 161, in insightface_loader
    raise Exception(e)
Exception: DLL load failed while importing onnx_cpp2py_export: A dynamic link library (DLL) initialization routine failed.

2024-10-10 22:34:13,155 - root - INFO - Prompt executed in 15.79 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":20,"last_link_id":36,"nodes":[{"id":8,"type":"VAEDecode","pos":{"0":1640,"1":710},"size":{"0":140,"1":46},"flags":{},"order":8,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":3,"type":"KSampler","pos":{"0":1280,"1":710},"size":{"0":315,"1":262},"flags":{},"order":7,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":32},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[0,"fixed",30,6.5,"ddpm","karras",1]},{"id":9,"type":"SaveImage","pos":{"0":1830,"1":700},"size":{"0":529.7760009765625,"1":582.3048095703125},"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["IPAdapter"]},{"id":5,"type":"EmptyLatentImage","pos":{"0":870,"1":1100},"size":{"0":315,"1":106},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[1024,1024,1]},{"id":6,"type":"CLIPTextEncode","pos":{"0":760,"1":620},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["a watercolor painting of a woman on the beach\n\nhigh quality artistry"]},{"id":7,"type":"CLIPTextEncode","pos":{"0":760,"1":850},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["photo, blurry, noisy, messy, lowres, jpeg, artifacts, ill, distorted, malformed, naked"]},{"id":18,"type":"IPAdapterFaceID","pos":{"0":850,"1":190},"size":{"0":315,"1":322},"flags":{},"order":6,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":35},{"name":"ipadapter","type":"IPADAPTER","link":34,"slot_index":1},{"name":"image","type":"IMAGE","link":29},{"name":"image_negative","type":"IMAGE","link":null},{"name":"attn_mask","type":"MASK","link":null},{"name":"clip_vision","type":"CLIP_VISION","link":null},{"name":"insightface","type":"INSIGHTFACE","link":null}],"outputs":[{"name":"MODEL","type":"MODEL","links":[32],"slot_index":0,"shape":3},{"name":"face_image","type":"IMAGE","links":null,"shape":3}],"properties":{"Node name for S&R":"IPAdapterFaceID"},"widgets_values":[0.65,1,"linear","concat",0,1,"V only"]},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":10,"1":680},"size":{"0":315,"1":98},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[36],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["dreamshaperXL_v21TurboDPMSDE.safetensors"]},{"id":20,"type":"IPAdapterUnifiedLoaderFaceID","pos":{"0":460,"1":60},"size":{"0":315,"1":126},"flags":{},"order":3,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":36},{"name":"ipadapter","type":"IPADAPTER","link":null}],"outputs":[{"name":"MODEL","type":"MODEL","links":[35],"slot_index":0,"shape":3},{"name":"ipadapter","type":"IPADAPTER","links":[34],"shape":3}],"properties":{"Node name for S&R":"IPAdapterUnifiedLoaderFaceID"},"widgets_values":["FACEID PORTRAIT (style transfer)",0.6,"CPU"]},{"id":12,"type":"LoadImage","pos":{"0":450,"1":240},"size":{"0":315,"1":314},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[29],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["1728542201_pose_0001.png","image"]}],"links":[[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"],[29,12,0,18,2,"IMAGE"],[32,18,0,3,0,"MODEL"],[34,20,1,18,1,"IPADAPTER"],[35,20,0,18,0,"MODEL"],[36,4,0,20,0,"MODEL"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[26.768776795340955,-65.38821301113899]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```
I used the [ipadapter_portrait workflow](https://github.com/cubiq/ComfyUI_IPAdapter_plus/blob/main/examples/ipadapter_portrait.json).

**Comment by ductiletoaster** [comment]
Got this to work. Referenced this thread.
https://github.com/onnx/onnx/issues/6267

```bash
pip install onnxruntime==1.16.1 onnx==1.16.1 onnxruntime-gpu==1.16.1
```

Not yet sure what combination of versions matter here but from what I can tell it is, as mentioned in the issue above, a problem with onnx and not the other packages.
