### ISSUE TITLE
IPAdapterUnifiedLoader Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by dalzin99** [cubiq/ComfyUI_IPAdapter_plus#710]
# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapterUnifiedLoader
- **Exception Type:** safetensors_rust.SafetensorError
- **Exception Message:** Error while deserializing header: HeaderTooLarge
## Stack Trace
```
  File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Volumes/Extreme Pro/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 564, in load_models
    self.clipvision['model'] = load_clip_vision(clipvision_file)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Volumes/Extreme Pro/ComfyUI/comfy/clip_vision.py", line 117, in load
    sd = load_torch_file(ckpt_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Volumes/Extreme Pro/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Volumes/Extreme Pro/ComfyUI/env/lib/python3.12/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-12-g967867d
- **Arguments:** main.py --force-fp16
- **OS:** posix
- **Python Version:** 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1
## Devices

- **Name:** mps
  - **Type:** mps
  - **VRAM Total:** 19327352832
  - **VRAM Free:** 7745208320
  - **Torch VRAM Total:** 19327352832
  - **Torch VRAM Free:** 7745208320

## Logs
```
2024-09-09 00:38:59,254 - root - INFO - Total VRAM 18432 MB, total RAM 18432 MB
2024-09-09 00:38:59,254 - root - INFO - pytorch version: 2.4.1
2024-09-09 00:38:59,255 - root - INFO - Forcing FP16.
2024-09-09 00:38:59,255 - root - INFO - Set vram state to: SHARED
2024-09-09 00:38:59,255 - root - INFO - Device: mps
2024-09-09 00:39:01,265 - root - INFO - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-09-09 00:39:03,743 - root - INFO - [Prompt Server] web root: /Volumes/Extreme Pro/ComfyUI/web
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path checkpoints /Volumes/Extreme Pro/stable-diffusion-webui/models/Stable-diffusion
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path configs /Volumes/Extreme Pro/stable-diffusion-webui/models/Stable-diffusion
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path vae /Volumes/Extreme Pro/stable-diffusion-webui/models/VAE
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path loras /Volumes/Extreme Pro/stable-diffusion-webui/models/Lora
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path loras /Volumes/Extreme Pro/stable-diffusion-webui/models/LyCORIS
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path upscale_models /Volumes/Extreme Pro/stable-diffusion-webui/models/ESRGAN
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path upscale_models /Volumes/Extreme Pro/stable-diffusion-webui/models/RealESRGAN
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path upscale_models /Volumes/Extreme Pro/stable-diffusion-webui/models/SwinIR
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path embeddings /Volumes/Extreme Pro/stable-diffusion-webui/embeddings
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path hypernetworks /Volumes/Extreme Pro/stable-diffusion-webui/models/hypernetworks
2024-09-09 00:39:03,747 - root - INFO - Adding extra search path controlnet /Volumes/Extreme Pro/stable-diffusion-webui/models/ControlNet
2024-09-09 00:39:08,809 - root - INFO - 
Import times for custom nodes:
2024-09-09 00:39:08,809 - root - INFO -    0.0 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/websocket_image_save.py
2024-09-09 00:39:08,809 - root - INFO -    0.0 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-09-09 00:39:08,809 - root - INFO -    0.0 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/ComfyUI_essentials
2024-09-09 00:39:08,809 - root - INFO -    0.0 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-09-09 00:39:08,809 - root - INFO -    0.1 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/efficiency-nodes-comfyui
2024-09-09 00:39:08,809 - root - INFO -    0.1 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
2024-09-09 00:39:08,809 - root - INFO -    0.1 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/ComfyUI-Manager
2024-09-09 00:39:08,809 - root - INFO -    0.2 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/clipseg.py
2024-09-09 00:39:08,809 - root - INFO -    1.3 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
2024-09-09 00:39:08,809 - root - INFO -    2.3 seconds: /Volumes/Extreme Pro/ComfyUI/custom_nodes/comfyui-reactor-node
2024-09-09 00:39:08,809 - root - INFO - 
2024-09-09 00:39:08,818 - root - INFO - Starting server

2024-09-09 00:39:08,818 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-09 00:39:36,978 - root - INFO - got prompt
2024-09-09 00:39:37,358 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-09-09 00:39:37,359 - root - INFO - model_type EPS
2024-09-09 00:39:46,736 - root - INFO - Using split attention in VAE
2024-09-09 00:39:46,738 - root - INFO - Using split attention in VAE
2024-09-09 00:39:48,182 - root - INFO - Requested to load SD1ClipModel
2024-09-09 00:39:48,182 - root - INFO - Loading 1 new model
2024-09-09 00:39:48,187 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-09-09 00:39:49,680 - root - ERROR - !!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
2024-09-09 00:39:49,685 - root - ERROR - Traceback (most recent call last):
  File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Volumes/Extreme Pro/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Extreme Pro/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 564, in load_models
    self.clipvision['model'] = load_clip_vision(clipvision_file)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Extreme Pro/ComfyUI/comfy/clip_vision.py", line 117, in load
    sd = load_torch_file(ckpt_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Extreme Pro/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Extreme Pro/ComfyUI/env/lib/python3.12/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

2024-09-09 00:39:49,686 - root - INFO - Prompt executed in 12.70 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":20,"last_link_id":36,"nodes":[{"id":8,"type":"VAEDecode","pos":{"0":1209,"1":188},"size":{"0":210,"1":46},"flags":{},"order":9,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"}},{"id":9,"type":"SaveImage","pos":{"0":1451,"1":189},"size":{"0":210,"1":58},"flags":{},"order":10,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":5,"type":"EmptyLatentImage","pos":{"0":518,"1":875},"size":{"0":315,"1":106},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":7,"type":"CLIPTextEncode","pos":{"0":466,"1":636},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":10,"type":"IPAdapterFaceID","pos":{"0":-77,"1":401},"size":{"0":317.4000244140625,"1":322},"flags":{},"order":3,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":null},{"name":"ipadapter","type":"IPADAPTER","link":null},{"name":"image","type":"IMAGE","link":14},{"name":"image_negative","type":"IMAGE","link":null},{"name":"attn_mask","type":"MASK","link":null},{"name":"clip_vision","type":"CLIP_VISION","link":null},{"name":"insightface","type":"INSIGHTFACE","link":null}],"outputs":[{"name":"MODEL","type":"MODEL","links":[],"slot_index":0,"shape":3},{"name":"face_image","type":"IMAGE","links":null,"shape":3}],"properties":{"Node name for S&R":"IPAdapterFaceID"},"widgets_values":[1,1,"linear","concat",0,1,"V only"]},{"id":6,"type":"CLIPTextEncode","pos":{"0":450,"1":363},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":28}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful scenery nature glass bottle landscape, , purple galaxy bottle,"]},{"id":3,"type":"KSampler","pos":{"0":1013,"1":532},"size":{"0":315,"1":262},"flags":{},"order":8,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":31},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[1062011546099321,"randomize",20,8,"euler","normal",1]},{"id":12,"type":"LoadImage","pos":{"0":-513,"1":842},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[14,32],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ComfyUI_00048_.png","image"]},{"id":19,"type":"IPAdapter","pos":{"0":144,"1":797},"size":{"0":315,"1":190},"flags":{},"order":7,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":35},{"name":"ipadapter","type":"IPADAPTER","link":34},{"name":"image","type":"IMAGE","link":32},{"name":"attn_mask","type":"MASK","link":null}],"outputs":[{"name":"MODEL","type":"MODEL","links":[31],"shape":3}],"properties":{"Node name for S&R":"IPAdapter"},"widgets_values":[1,0,1,"standard"]},{"id":20,"type":"IPAdapterUnifiedLoader","pos":{"0":-492,"1":572},"size":{"0":315,"1":78},"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":36},{"name":"ipadapter","type":"IPADAPTER","link":null}],"outputs":[{"name":"model","type":"MODEL","links":[35],"slot_index":0,"shape":3},{"name":"ipadapter","type":"IPADAPTER","links":[34],"shape":3}],"properties":{"Node name for S&R":"IPAdapterUnifiedLoader"},"widgets_values":["PLUS FACE (portraits)"]},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":-790,"1":185},"size":{"0":315,"1":98},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[36],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[5,28],"slot_index":1},{"name":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["onemix Realistic face v3 sd1.5.safetensors"]}],"links":[[2,5,0,3,3,"LATENT"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"],[14,12,0,10,2,"IMAGE"],[28,4,1,6,0,"CLIP"],[31,19,0,3,0,"MODEL"],[32,12,0,19,2,"IMAGE"],[34,20,1,19,1,"IPADAPTER"],[35,20,0,19,0,"MODEL"],[36,4,0,20,0,"MODEL"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7513148009015783,"offset":[618.0604017287056,-128.6061850905183]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by cubiq** [comment]
the clip vision model might be corrupted or simply using the wrong file

**Comment by cubiq** [comment]
closing for inactivity, feel free to reopen if you still have issues

**Comment by jinnaluo0** [comment]
在utils.py里写了个print,然后后台输出：
***************************************** D:\ComfyUI-aki-v1.4\ComfyUI-aki-v1.4\models\ipadapter\._ip-adapter-plus_sdxl_vit-h.safetensors
检查文件夹后，发现好些个隐藏文件：
![微信图片_20241102171734](https://github.com/user-attachments/assets/47197648-1b50-47bf-89f9-f9b151bccc10)
把这些隐藏文件删除后，问题解决。

**Comment by jinnaluo0** [comment]
所以，为什么会产生这些隐藏文件？

**Comment by LIULE1** [comment]
隐藏文件都删掉了，但是问题还是没有解决
![image](https://github.com/user-attachments/assets/b1e3ebbf-9d16-40b7-8076-f76ba31404de)

**Comment by LIULE1** [comment]
![image](https://github.com/user-attachments/assets/52aea638-ecb3-4b17-98fb-baa001cb18f4)
