### ISSUE TITLE
'NoneType' object has no attribute 'patcher'

### ISSUE THREAD

**Issue by Gamebropro** [cubiq/ComfyUI_IPAdapter_plus#728]
# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapter
- **Exception Type:** AttributeError
- **Exception Message:** 'NoneType' object has no attribute 'patcher'
## Stack Trace
```
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 726, in apply_ipadapter
    return ipadapter_execute(model.clone(), ipadapter['ipadapter']['model'], ipadapter['clipvision']['model'], **ipa_args)

  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 359, in ipadapter_execute
    img_cond_embeds = encode_image_masked(clipvision, image, batch_size=encode_batch_size, tiles=enhance_tiles, ratio=enhance_ratio, clipvision_size=clipvision_size)

  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 242, in encode_image_masked
    embeds = encode_image_masked_(clip_vision, image, mask, batch_size, clipvision_size=clipvision_size)

  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 281, in encode_image_masked_
    model_management.load_model_gpu(clip_vision.patcher)

```
## System Information
- **ComfyUI Version:** v0.2.2-82-ga9e459c
- **Arguments:** D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\main.py --highvram --preview-method auto --preview-method taesd --use-pytorch-cross-attention --auto-launch --fp8_e5m2-unet
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce GTX 1650 SUPER : native
  - **Type:** cuda
  - **VRAM Total:** 4294639616
  - **VRAM Free:** 1836646912
  - **Torch VRAM Total:** 1644167168
  - **Torch VRAM Free:** 40960512

## Logs
```
2024-09-30 03:26:00,230 - root - INFO - Total VRAM 4096 MB, total RAM 16294 MB
2024-09-30 03:26:00,230 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-30 03:26:00,232 - root - INFO - Set vram state to: HIGH_VRAM
2024-09-30 03:26:00,232 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1650 SUPER : native
2024-09-30 03:26:12,635 - root - INFO - Using pytorch cross attention
2024-09-30 03:26:23,846 - root - INFO - [Prompt Server] web root: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\web
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path checkpoints D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\StableDiffusion
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path vae D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\VAE
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path loras D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\Lora
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path loras D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\LyCORIS
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path upscale_models D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\ESRGAN
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path upscale_models D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\RealESRGAN
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path upscale_models D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\SwinIR
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path embeddings D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\TextualInversion
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path hypernetworks D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\Hypernetwork
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path controlnet D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\ControlNet
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path controlnet D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\T2IAdapter
2024-09-30 03:26:23,859 - root - INFO - Adding extra search path clip D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\CLIP
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path clip_vision D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\InvokeClipVision
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path diffusers D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\Diffusers
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path gligen D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\GLIGEN
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path vae_approx D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\ApproxVAE
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path ipadapter D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\IpAdapter
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path ipadapter D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\InvokeIpAdapters15
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path ipadapter D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\InvokeIpAdaptersXl
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path prompt_expansion D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\PromptExpansion
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path ultralytics D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\Ultralytics
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path ultralytics_bbox D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\Ultralytics\bbox
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path ultralytics_segm D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\Ultralytics\segm
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path sams D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\Sams
2024-09-30 03:26:23,861 - root - INFO - Adding extra search path diffusion_models D:\SD WEB UI\StabilityMatrix-win-x64\Data\Models\unet
2024-09-30 03:26:51,140 - root - INFO - Total VRAM 4096 MB, total RAM 16294 MB
2024-09-30 03:26:51,140 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-30 03:26:51,141 - root - INFO - Set vram state to: HIGH_VRAM
2024-09-30 03:26:51,141 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1650 SUPER : native
2024-09-30 03:27:17,833 - root - INFO - 
Import times for custom nodes:
2024-09-30 03:27:17,833 - root - INFO -    0.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Image-Selector
2024-09-30 03:27:17,833 - root - INFO -    0.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
2024-09-30 03:27:17,833 - root - INFO -    0.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyLiterals
2024-09-30 03:27:17,833 - root - INFO -    0.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-30 03:27:17,833 - root - INFO -    0.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-09-30 03:27:17,833 - root - INFO -    0.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\cg-use-everywhere
2024-09-30 03:27:17,833 - root - INFO -    0.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-09-30 03:27:17,833 - root - INFO -    0.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
2024-09-30 03:27:17,833 - root - INFO -    0.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfy-image-saver
2024-09-30 03:27:17,833 - root - INFO -    0.1 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-09-30 03:27:17,833 - root - INFO -    0.1 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-09-30 03:27:17,833 - root - INFO -    0.1 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-09-30 03:27:17,834 - root - INFO -    0.1 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
2024-09-30 03:27:17,834 - root - INFO -    0.1 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-various
2024-09-30 03:27:17,834 - root - INFO -    0.1 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-30 03:27:17,834 - root - INFO -    0.1 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-animatediff
2024-09-30 03:27:17,834 - root - INFO -    0.1 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-30 03:27:17,834 - root - INFO -    0.1 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-09-30 03:27:17,834 - root - INFO -    0.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-09-30 03:27:17,834 - root - INFO -    0.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-fastblend
2024-09-30 03:27:17,834 - root - INFO -    0.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-30 03:27:17,834 - root - INFO -    0.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-09-30 03:27:17,834 - root - INFO -    0.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
2024-09-30 03:27:17,834 - root - INFO -    0.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-09-30 03:27:17,834 - root - INFO -    0.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
2024-09-30 03:27:17,834 - root - INFO -    0.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-30 03:27:17,835 - root - INFO -    0.3 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
2024-09-30 03:27:17,835 - root - INFO -    0.4 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-30 03:27:17,835 - root - INFO -    0.5 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-30 03:27:17,835 - root - INFO -    0.5 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-30 03:27:17,835 - root - INFO -    0.5 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-30 03:27:17,835 - root - INFO -    0.7 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui_face_parsing
2024-09-30 03:27:17,835 - root - INFO -    0.8 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-30 03:27:17,835 - root - INFO -    1.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-09-30 03:27:17,835 - root - INFO -    1.6 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-09-30 03:27:17,835 - root - INFO -    1.6 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-09-30 03:27:17,835 - root - INFO -    1.8 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Documents
2024-09-30 03:27:17,835 - root - INFO -    2.4 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfyui-tensorops
2024-09-30 03:27:17,835 - root - INFO -    2.6 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-09-30 03:27:17,835 - root - INFO -    3.0 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-ControlNeXt-SVD
2024-09-30 03:27:17,835 - root - INFO -    3.5 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Gemini
2024-09-30 03:27:17,835 - root - INFO -    3.6 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-09-30 03:27:17,835 - root - INFO -    4.3 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-EbSynth
2024-09-30 03:27:17,835 - root - INFO -    6.8 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\comfy_mtb
2024-09-30 03:27:17,836 - root - INFO -   10.2 seconds: D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-09-30 03:27:17,836 - root - INFO - 
2024-09-30 03:27:17,854 - root - INFO - Starting server

2024-09-30 03:27:17,855 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-30 03:27:33,088 - root - INFO - got prompt
2024-09-30 03:27:35,829 - root - INFO - model weight dtype torch.float8_e5m2, manual cast: torch.float32
2024-09-30 03:27:35,915 - root - INFO - model_type EPS
2024-09-30 03:27:57,336 - root - INFO - Using pytorch attention in VAE
2024-09-30 03:27:57,337 - root - INFO - Using pytorch attention in VAE
2024-09-30 03:27:59,071 - root - INFO - Requested to load SD1ClipModel
2024-09-30 03:27:59,071 - root - INFO - Loading 1 new model
2024-09-30 03:27:59,075 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-09-30 03:28:02,412 - root - INFO - loaded straight to GPU
2024-09-30 03:28:02,412 - root - INFO - Requested to load BaseModel
2024-09-30 03:28:02,413 - root - INFO - Loading 1 new model
2024-09-30 03:28:02,429 - root - INFO - loaded completely 0.0 819.703067779541 True
2024-09-30 03:29:10,184 - root - ERROR - !!! Exception during processing !!! Error while deserializing header: HeaderTooSmall
2024-09-30 03:29:10,261 - root - ERROR - Traceback (most recent call last):
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 564, in load_models
    self.clipvision['model'] = load_clip_vision(clipvision_file)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\clip_vision.py", line 117, in load
    sd = load_torch_file(ckpt_path)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\safetensors\torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall

2024-09-30 03:29:10,263 - root - INFO - Prompt executed in 97.14 seconds
2024-09-30 03:29:34,718 - root - INFO - got prompt
2024-09-30 03:29:38,708 - root - ERROR - !!! Exception during processing !!! 'NoneType' object has no attribute 'patcher'
2024-09-30 03:29:38,727 - root - ERROR - Traceback (most recent call last):
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 726, in apply_ipadapter
    return ipadapter_execute(model.clone(), ipadapter['ipadapter']['model'], ipadapter['clipvision']['model'], **ipa_args)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 359, in ipadapter_execute
    img_cond_embeds = encode_image_masked(clipvision, image, batch_size=encode_batch_size, tiles=enhance_tiles, ratio=enhance_ratio, clipvision_size=clipvision_size)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 242, in encode_image_masked
    embeds = encode_image_masked_(clip_vision, image, mask, batch_size, clipvision_size=clipvision_size)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 281, in encode_image_masked_
    model_management.load_model_gpu(clip_vision.patcher)
AttributeError: 'NoneType' object has no attribute 'patcher'

2024-09-30 03:29:38,729 - root - INFO - Prompt executed in 3.97 seconds
2024-09-30 03:29:53,230 - root - INFO - got prompt
2024-09-30 03:29:53,391 - root - ERROR - !!! Exception during processing !!! 'NoneType' object has no attribute 'patcher'
2024-09-30 03:29:53,391 - root - ERROR - Traceback (most recent call last):
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 726, in apply_ipadapter
    return ipadapter_execute(model.clone(), ipadapter['ipadapter']['model'], ipadapter['clipvision']['model'], **ipa_args)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 359, in ipadapter_execute
    img_cond_embeds = encode_image_masked(clipvision, image, batch_size=encode_batch_size, tiles=enhance_tiles, ratio=enhance_ratio, clipvision_size=clipvision_size)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 242, in encode_image_masked
    embeds = encode_image_masked_(clip_vision, image, mask, batch_size, clipvision_size=clipvision_size)
  File "D:\SD WEB UI\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 281, in encode_image_masked_
    model_management.load_model_gpu(clip_vision.patcher)
AttributeError: 'NoneType' object has no attribute 'patcher'

2024-09-30 03:29:53,393 - root - INFO - Prompt executed in 0.12 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
![Screenshot 2024-09-30 033103](https://github.com/user-attachments/assets/06b4a052-6b93-4d2a-9ec3-80139c2c7d50)

**Comment by Gamebropro** [comment]
[harsh_durgude_workflow_comfyworkflows.json](https://github.com/user-attachments/files/17181486/harsh_durgude_workflow_comfyworkflows.json)

**Comment by Zooloos007** [comment]
Any solution?
