### ISSUE TITLE
IPAdapterUnifiedLoader ------ IPAdapter model not found

### ISSUE THREAD

**Issue by Innosolsinfo1** [cubiq/ComfyUI_IPAdapter_plus#732]
![image](https://github.com/user-attachments/assets/fb453529-1098-4584-9f80-638f26367fa2)

# ComfyUI Error Report

## Error Details
- **Node Type:** IPAdapterUnifiedLoader
- **Exception Type:** Exception
- **Exception Message:** IPAdapter model not found.
## Stack Trace
```
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 573, in load_models
    raise Exception("IPAdapter model not found.")

```
## System Information
- **ComfyUI Version:** v0.2.0-1-gd043997
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884246528
  - **VRAM Free:** 6645773752
  - **Torch VRAM Total:** 5167382528
  - **Torch VRAM Free:** 32404920

## Logs
```
2024-10-07 13:16:37,584 - root - INFO - Total VRAM 12287 MB, total RAM 32694 MB
2024-10-07 13:16:37,585 - root - INFO - pytorch version: 2.4.0+cu121
2024-10-07 13:16:37,586 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-07 13:16:37,586 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-10-07 13:16:38,840 - root - INFO - Using pytorch cross attention
2024-10-07 13:16:41,622 - root - INFO - [Prompt Server] web root: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-10-07 13:16:42,950 - root - WARNING - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4\__init__.py", line 6, in <module>
    import bitsandbytes
ModuleNotFoundError: No module named 'bitsandbytes'

2024-10-07 13:16:42,950 - root - WARNING - Cannot import D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4 module for custom nodes: No module named 'bitsandbytes'
2024-10-07 13:16:43,865 - root - INFO - 
Import times for custom nodes:
2024-10-07 13:16:43,865 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-07 13:16:43,866 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
2024-10-07 13:16:43,866 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SD3LatentSelectRes
2024-10-07 13:16:43,867 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
2024-10-07 13:16:43,867 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-07 13:16:43,867 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-07 13:16:43,868 - root - INFO -    0.0 seconds (IMPORT FAILED): D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
2024-10-07 13:16:43,868 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-07 13:16:43,868 - root - INFO -    0.3 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-07 13:16:43,869 - root - INFO -    0.9 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-07 13:16:43,869 - root - INFO - 
2024-10-07 13:16:43,875 - root - INFO - Starting server

2024-10-07 13:16:43,875 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-07 13:17:10,888 - root - INFO - got prompt
2024-10-07 13:17:11,535 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-07 13:17:11,544 - root - INFO - model_type EPS
2024-10-07 13:17:26,832 - root - INFO - Using pytorch attention in VAE
2024-10-07 13:17:26,834 - root - INFO - Using pytorch attention in VAE
2024-10-07 13:17:27,826 - root - INFO - Requested to load SDXLClipModel
2024-10-07 13:17:27,826 - root - INFO - Loading 1 new model
2024-10-07 13:17:27,840 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-07 13:17:32,525 - root - INFO - loaded straight to GPU
2024-10-07 13:17:32,526 - root - INFO - Requested to load SDXL
2024-10-07 13:17:32,526 - root - INFO - Loading 1 new model
2024-10-07 13:17:34,986 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-10-07 13:17:42,839 - root - ERROR - !!! Exception during processing !!! IPAdapter model not found.
2024-10-07 13:17:42,867 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 573, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

2024-10-07 13:17:42,870 - root - INFO - Prompt executed in 31.98 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":20,"last_link_id":33,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":{"0":-22,"1":353,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":7,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[20],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":6,"type":"CLIPTextEncode","pos":{"0":-30,"1":138,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[19],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["Two person standing and doing handshake, and one person on the left has thumbs up"]},{"id":18,"type":"LoadImage","pos":{"0":-478,"1":-32,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[27],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["Reference.png","image"]},{"id":12,"type":"LoadImage","pos":{"0":-900,"1":612,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[15,17],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["Whiteboard.png","image"]},{"id":15,"type":"ImageInvert","pos":{"0":29,"1":875,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":26},"flags":{},"order":4,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":17}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[18],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"ImageInvert"}},{"id":14,"type":"ControlNetApplyAdvanced","pos":{"0":514,"1":592,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":340.20001220703125,"1":166},"flags":{},"order":10,"mode":0,"inputs":[{"name":"positive","type":"CONDITIONING","link":19},{"name":"negative","type":"CONDITIONING","link":20},{"name":"control_net","type":"CONTROL_NET","link":23},{"name":"image","type":"IMAGE","link":18}],"outputs":[{"name":"positive","type":"CONDITIONING","links":[21],"slot_index":0,"shape":3},{"name":"negative","type":"CONDITIONING","links":[22],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"ControlNetApplyAdvanced"},"widgets_values":[0.6,0,0.6]},{"id":19,"type":"PreviewImage","pos":{"0":1542,"1":85,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":26},"flags":{},"order":13,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":24}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}},{"id":9,"type":"SaveImage","pos":{"0":1531,"1":226,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":58},"flags":{},"order":14,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":26}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":8,"type":"VAEDecode","pos":{"0":1286,"1":188,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":46},"flags":{},"order":12,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[24,26],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"}},{"id":3,"type":"KSampler","pos":{"0":845,"1":-64,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":262},"flags":{},"order":11,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":13},{"name":"positive","type":"CONDITIONING","link":21},{"name":"negative","type":"CONDITIONING","link":22},{"name":"latent_image","type":"LATENT","link":16}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[802885821190995,"randomize",20,8,"euler","normal",1]},{"id":17,"type":"ControlNetLoader","pos":{"0":-63,"1":729,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":58},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[23],"shape":3}],"properties":{"Node name for S&R":"ControlNetLoader"},"widgets_values":["diffusion_pytorch_model.fp16.safetensors"]},{"id":13,"type":"VAEEncode","pos":{"0":53,"1":591,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":46},"flags":{},"order":8,"mode":0,"inputs":[{"name":"pixels","type":"IMAGE","link":15},{"name":"vae","type":"VAE","link":14}],"outputs":[{"name":"LATENT","type":"LATENT","links":[16],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAEEncode"}},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":-981,"1":270,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":98},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[31],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","type":"VAE","links":[8,14],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["ProteusV0.3.safetensors"]},{"id":11,"type":"IPAdapterAdvanced","pos":{"0":259,"1":-194,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":278},"flags":{},"order":9,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":32},{"name":"ipadapter","type":"IPADAPTER","link":33},{"name":"image","type":"IMAGE","link":27},{"name":"image_negative","type":"IMAGE","link":null},{"name":"attn_mask","type":"MASK","link":null},{"name":"clip_vision","type":"CLIP_VISION","link":null}],"outputs":[{"name":"MODEL","type":"MODEL","links":[13],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"IPAdapterAdvanced"},"widgets_values":[1,"linear","concat",0,1,"V only"]},{"id":20,"type":"IPAdapterUnifiedLoader","pos":{"0":-754.6527709960938,"1":-169.59332275390625,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":78},"flags":{},"order":5,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":31},{"name":"ipadapter","type":"IPADAPTER","link":null}],"outputs":[{"name":"model","type":"MODEL","links":[32],"shape":3},{"name":"ipadapter","type":"IPADAPTER","links":[33],"shape":3}],"properties":{"Node name for S&R":"IPAdapterUnifiedLoader"},"widgets_values":["PLUS (high strength)"]}],"links":[[3,4,1,6,0,"CLIP"],[5,4,1,7,0,"CLIP"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[13,11,0,3,0,"MODEL"],[14,4,2,13,1,"VAE"],[15,12,0,13,0,"IMAGE"],[16,13,0,3,3,"LATENT"],[17,12,0,15,0,"IMAGE"],[18,15,0,14,3,"IMAGE"],[19,6,0,14,0,"CONDITIONING"],[20,7,0,14,1,"CONDITIONING"],[21,14,0,3,1,"CONDITIONING"],[22,14,1,3,2,"CONDITIONING"],[23,17,0,14,2,"CONTROL_NET"],[24,8,0,19,0,"IMAGE"],[26,8,0,9,0,"IMAGE"],[27,18,0,11,2,"IMAGE"],[31,4,0,20,0,"MODEL"],[32,20,0,11,0,"MODEL"],[33,20,1,11,1,"IPADAPTER"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[955,269]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by Innosolsinfo1** [comment]
OK I re-installed the IPAdapterplus through git and its fixed
