### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Resampler:         size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1664]).

### ISSUE THREAD

**Issue by chrisprojs** [cubiq/ComfyUI_IPAdapter_plus#78]
Prompt executed in 22.38 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\chris\OneDrive\Desktop\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\chris\OneDrive\Desktop\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\chris\OneDrive\Desktop\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\chris\OneDrive\Desktop\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 367, in apply_ipadapter
    self.ipadapter = IPAdapter(
  File "C:\Users\chris\OneDrive\Desktop\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 161, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
  File "C:\Users\chris\OneDrive\Desktop\ComfyUI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resampler:
        size mismatch for proj_in.weight: copying a param with shape torch.Size([1280, 1280]) from checkpoint, the shape in current model is torch.Size([1280, 1664]).

Prompt executed in 20.86 seconds

**Comment by cubiq** [comment]
you are using the SDXL image encoder with a vit-h model. All vit-h models require "SD1.5" encoder, even if they are for SDXL.

**Comment by somebush** [comment]
> you are using the SDXL image encoder with a vit-h model. All vit-h models require "SD1.5" encoder, even if they are for SDXL.

where can I get the sdxl model for ip adapter?

**Comment by wangwenqiao666** [comment]
so how do you solve this problem?

**Comment by ttulttul** [comment]
Make sure that, if your checkpoint is an SDXL-based checkpoint, all the other models in other nodes that may process output from that checkpoint are suitable for SDXL. For instance, make sure that IPAdapter is being supplied with the XL version of the IPAdapter model.
