### ISSUE TITLE
'ModuleList' object has no attribute '1' when trying to use canny example

### ISSUE THREAD

**Issue by oxysoft** [cubiq/ComfyUI_IPAdapter_plus#8]
```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1236, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1206, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 93, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 644, in sample
    pre_run_control(self.model_wrap, negative + positive)
  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 488, in pre_run_control
    x[1]['control'].pre_run(model.inner_model.inner_model, percent_to_timestep_function)
  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 269, in pre_run
    comfy.utils.set_attr(self.control_model, k, self.control_weights[k].to(dtype).to(comfy.model_management.get_torch_device()))
  File "D:\Projects\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 264, in set_attr
    obj = getattr(obj, name)
  File "D:\Projects\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleList' object has no attribute '1'
```

**Comment by oxysoft** [comment]
I forgot to set the controlnet and the default was a SDXL controlnet

**Comment by AmpleProject** [comment]
Hey! I'm getting this error when prompting with ControlNet, would you know why? Thank you so much in advance for your time!

`Error occurred when executing KSamplerAdvanced:

'ModuleList' object has no attribute '1'

  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1389, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1325, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 615, in sample
    pre_run_control(model, negative + positive)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 452, in pre_run_control
    x['control'].pre_run(model, percent_to_timestep_function)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 296, in pre_run
    comfy.utils.set_attr(self.control_model, k, self.control_weights[k].to(dtype).to(comfy.model_management.get_torch_device()))
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 279, in set_attr
    obj = getattr(obj, name)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
Queue size: 0
Extra options
`

**Comment by AmpleProject** [comment]
Hey! I'm getting this error when prompting with ControlNet, would you know why? Thank you so much in advance for your time!

````
Error occurred when executing KSamplerAdvanced:

'ModuleList' object has no attribute '1'

  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1389, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1325, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 615, in sample
    pre_run_control(model, negative + positive)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 452, in pre_run_control
    x['control'].pre_run(model, percent_to_timestep_function)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 296, in pre_run
    comfy.utils.set_attr(self.control_model, k, self.control_weights[k].to(dtype).to(comfy.model_management.get_torch_device()))
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 279, in set_attr
    obj = getattr(obj, name)
  File "D:\Archivos de programas\StableDiffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
````

**Comment by datuizhuang** [comment]
same error

**Comment by user9yc** [comment]
Error occurred when executing KSampler (Efficient):

'ModuleList' object has no attribute '1'

File "F:\Comfy UI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\Comfy UI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\Comfy UI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\Comfy UI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 700, in sample
samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
File "F:\Comfy UI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 533, in process_latent_image
samples = KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
File "F:\Comfy UI\ComfyUI\nodes.py", line 1375, in sample
return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
File "F:\Comfy UI\ComfyUI\nodes.py", line 1345, in common_ksampler
samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
File "F:\Comfy UI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
File "F:\Comfy UI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 334, in motion_sample
latents = wrap_function_to_inject_xformers_bug_info(orig_comfy_sample)(model, noise, *args, **kwargs)
File "F:\Comfy UI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\utils_model.py", line 216, in wrapped_function
return function_to_wrap(*args, **kwargs)
File "F:\Comfy UI\ComfyUI\comfy\sample.py", line 100, in sample
samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
File "F:\Comfy UI\ComfyUI\comfy\samplers.py", line 712, in sample
return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
File "F:\Comfy UI\ComfyUI\comfy\samplers.py", line 611, in sample
pre_run_control(model, negative + positive)
File "F:\Comfy UI\ComfyUI\comfy\samplers.py", line 448, in pre_run_control
x['control'].pre_run(model, percent_to_timestep_function)
File "F:\Comfy UI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 399, in pre_run_inject
self.base.pre_run(model, percent_to_timestep_function)
File "F:\Comfy UI\ComfyUI\comfy\controlnet.py", line 296, in pre_run
comfy.utils.set_attr(self.control_model, k, self.control_weights[k].to(dtype).to(comfy.model_management.get_torch_device()))
File "F:\Comfy UI\ComfyUI\comfy\utils.py", line 279, in set_attr
obj = getattr(obj, name)
File "F:\Comfy UI\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1695, in __getattr__
raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

**Comment by Ken-g6** [comment]
I just tried to combine a workflow that has SD 1.5 and SDXL parts with a known-good SDXL hand detailer and got this error. I made certain the hand detailer was connected only to SDXL outputs. So I guess just having SD 1.5 stuff in the workflow can cause this error?
